### ISSUE TITLE
Discussion: new name!

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#108]
Hey everyone! I have a big refactor in the works with some breaking changes, and I thought I'd take this opportunity to re-release BA with a better name and a 1.0 version. 
The new release modularizes BA into a python package, which lets people import individual parts for their own uses (e.g. parsers, link archiving, screenshotting, indexing). It fixes a lot of the bad decisions I made early on (e.g. using timestamps as unique keys instead of sha256 hashes of the URLs). It also adds a backend with a web GUI for searching and adding imports.

The new name should be easy to find and type in a python packaging context and should be related to web archiving somehow.

Requirements for a new name:
 - one word
 - no symbols or spaces (since it's going to be imported as a python package like `from webfreeze.pocket import parse_links`
 - should be 1st in google results when released with a new name (i.e. no competing projects/keywords)
 - should be intuitively related to web archiving

Potential ideas:
 - WebFreeze
 - Freezekit
 - ArchiveKit
 - WebCooler

Comment with your name suggestions/ideas!

**Comment by pirate** [comment]
I think my official vote goes to `FreezeKit`, upvote/downvote this comment with the reaction emoji if you agree or disagree.

**Comment by f0086** [comment]
I like **WebFreeze** the most from your list.
Some random ideas (did not checked on google):

* HTTPFridge (Can be a cool (phun intended) logo wit ha Refridgerator)
* WebFridge

**Comment by gmcz** [comment]
Spitballing...

WebCryo
WebCopyKit
WebDowner
DownWeb
WebGemini
CopyLocker
Savetheweb
aaarchive (homage to @pirate's handle and can stand for "Always Available Archive")

**Comment by guilhas** [comment]
LinkShip
WebShip
ArkWeb
ArkMark
NetNotes

**Comment by Drowze** [comment]
ctrls (or ctrl-s)

**Comment by anarcat** [comment]
i like aaarchive... yaaaar! :)

**Comment by evaryont** [comment]
I don't know if you want to keep the reference to bookmarks, but if you do I'd suggest **FreezeMark**.

**Comment by pirate** [comment]
Haha @pigmonkey it's funny that you suggest that name, "memex" is used by a friend of mine for his project @hyfen https://hyfen.net/

My favorite candidates so far are:

 - Aaarchive
 - WebFridge
 - WebFreeze

**Comment by caltlgin** [comment]
Aaarchive gets my vote.

**Comment by f0086** [comment]
* HTTPreserver
* PagePreserver
* WebSafe
* WebShepherd
* PageShepherd

**Comment by guilhas** [comment]
ShipAway
Sharc

**Comment by darkeststar** [comment]
Bibliosoph (person in charge of a library)

**Comment by pirate** [comment]
<img width="717" alt="screen shot 2018-12-01 at 1 59 56 pm" src="https://user-images.githubusercontent.com/511499/49328448-69352400-f571-11e8-9a07-82a3c7b5f230.png">

I found a great icon if we go with WebFridge 😁

**Comment by ianchanning** [comment]
Barc (short form of Bookmark archiver, easily pronounceable, puppy friendly)

**Comment by pirate** [comment]
How about `ArchiveBox` as suggested by @FiloSottile? I like it because "box" implies it lives locally on your computer, and it's an intuitive CLI and package name too.  Also the only competition on google is from physical cardboard boxes on Amazon used for archiving documents.

```bash
cd ~/pirates-archive
archivebox init
archivebox add https://en.wikipedia.org/wiki/Beans
archivebox crawl --depth=2 https://en.wikipedia.org/wiki/List_of_lists_of_lists
archivebox publish --html /var/www
archivebox server --bind 127.0.0.1:8083
```

```python
from archivebox.crawl import rss
from archivebox.extract import media

links = crawl_rss(open('feed.rss', 'r').read())
assets = media.extract('https://youtube.com/watch?v=example')
```

Desktop/mobile/browser extension app name: `ArchiveBox.app` / `ArchiveBox.exe`

As much as I love aaarchive, I don't think it's a practical choice given an [aaarchive](https://github.com/aaarchive) group already exists on github and it's a bit hard to say in a way that's easy for people to google later.

**Comment by gmcz** [comment]
I’ll happily install `archivebox`, and if anyone really wants to use `aaarchive` you can always create a shell alias. 😉

**Comment by f0086** [comment]
ArchiveBox is IMHO a little too abstract.

**Comment by guilhas** [comment]
ArcBox also looks good.
ArkBox?
ArqBox?

**Comment by kodfodrasz** [comment]
But I think the current name is pretty good, but if you want a new name why not something pirate themed, like:

Stash
WebStash

**Comment by pirate** [comment]
Going with this plan: https://github.com/pirate/ArchiveBox/issues/108#issuecomment-445405537 outlined in the roadmap here: https://github.com/pirate/ArchiveBox/issues/120

**Comment by pirate** [comment]
Not considering renaming it at this point @codehangen, ArchiveBox is here to stay for now.
