### ISSUE TITLE
Add support for Windows 10

### ISSUE THREAD

**Issue by whalehub** [pirate/ArchiveBox#127]
**Is your feature request related to a problem? Please describe.**
The problem I'm facing is that I want to use ArchiveBox on Windows 10 but can't because it doesn't officially support it.

**Describe the solution you'd like**
I would like for you to provide an official way to install ArchiveBox on Windows 10.

**Describe alternatives you've considered**
I've considered setting up a Linux VM on my Windows 10 machine and running ArchiveBox on it, but it seems like a big hassle to go through this process for a single application.

**Additional context**
N/A

**Comment by pirate** [comment]
You can run it with Docker for windows: https://docs.docker.com/docker-for-windows/

This will take care of running an Ubuntu VM with ArchiveBox inside.  Let me know if you have any questions about getting that working.

**Comment by pirate** [comment]
@whalehub give this a shot: 
https://github.com/pirate/ArchiveBox/wiki/Install#docker-setup

**Comment by whalehub** [comment]
@pirate Thanks! This is a satisfactory solution for me.
