### ISSUE TITLE
Skip URL when timeout

### ISSUE THREAD

**Issue by Whiskat** [pirate/ArchiveBox#131]
When a URL is 404, it results in a Timeout. And then Archiver stops there until I press Ctrl-C. Then I have to  resume downloading, but no with that timestamp that always gives me Timeout, but with the next timestamp which I have to find in index.json.

**How could I configure the Archiver so when I get any kind of timeout, it automatically jumps to next timestamp URL?**

Sorry in advance, english is not my first language and I'm really new with programming.

**Comment by pirate** [comment]
Should be fixed as of 74e925d.

Download the latest master and give it a try.

Let me know if you're still having issues with commands running past their timeouts and I'll re-open the ticket.
