### ISSUE TITLE
Wiki: Fix docker run command for feed parsing

### ISSUE THREAD

**Issue by Strubbl** [pirate/ArchiveBox#140]
I have a small patch for the docker wiki site:

[0001-Fix-docker-run-command-for-feed-parsing.patch.txt](https://github.com/pirate/ArchiveBox/files/2858056/0001-Fix-docker-run-command-for-feed-parsing.patch.txt)

Did i overlook an edit button for the wiki? Otherwise i would have fixed it right there.

**Comment by pirate** [comment]
Thanks, will apply this patch! Wiki is set to only allow my edits because I don't want people changing docs without my confirmation that it matches the code.  You did the right thing here, issue is the way to go.
