### ISSUE TITLE
Ignore Pocket HTML titles if they are URLs

### ISSUE THREAD

**Issue by kristofferR** [pirate/ArchiveBox#144]
I don't know why, but a lot of the pages I've saved on Pocket don't have the proper title in ril_export.html, the raw URL is the title. On getpocket.com all pages have the proper titles.

![cleanshot 2019-02-15 at 13 05 07](https://user-images.githubusercontent.com/481270/52855780-bb262880-3122-11e9-9f10-056588201506.png)

It would be nice if ArchiveBox could ignore importing the title tag from links with links as the title tag, and instead grab the <title> tag from the HTML pages instead. Currently my ArchiveBox library is just a messy combination of proper titles and URLs:

![cleanshot 2019-02-15 at 13 16 14](https://user-images.githubusercontent.com/481270/52856162-ec532880-3123-11e9-86aa-cd9a1b7d9312.png)

**Comment by pirate** [comment]
This should be fixed in the latest master (1b36d5b), comment back if it's still not working and I'll reopoen the issue.

Run `./archive` twice to fix all the titles in your existing archive.
