### ISSUE TITLE
Add support for cookies.txt

### ISSUE THREAD

**Issue by flip111** [pirate/ArchiveBox#150]
netscape cookies format

Can just get cookies from a browser. For example with https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/

I don't have chrome now

**Comment by pirate** [comment]
Great idea! Just added it in d52c9c5.

Pull the latest `master` and give it a shot!

In the future we can do something like this to add cookies.txt support to the chrome headless archiving as well: https://stackoverflow.com/a/54227598
