### ISSUE TITLE
SSL problem with docker compose

### ISSUE THREAD

**Issue by flip111** [pirate/ArchiveBox#151]
Host system is ubuntu 18.10

![archivebox ssl](https://user-images.githubusercontent.com/2244480/53214169-7f6bf100-3643-11e9-8496-f93fc832509d.png)

[ArchiveBox SSL.txt](https://github.com/pirate/ArchiveBox/files/2892069/ArchiveBox.SSL.txt)

```
Secure Connection Failed

An error occurred during a connection to 127.0.0.1:8098. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG 
```

```
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by pirate** [comment]
The archive is served with HTTP, not HTTPS as it's intended to be put behind a reverse proxy of some sort when used with docker-compose (as is standard for docker-compose projects).

If you get the archive with HTTP it should work: `curl http://127.0.0.1:8089`.
