### ISSUE TITLE
Question about docker install

### ISSUE THREAD

**Issue by flip111** [pirate/ArchiveBox#152]
Hi i tried the normal docker install https://github.com/pirate/ArchiveBox/wiki/Docker#docker (without compose).

I get the following output which looks good:

```
» sudo docker run -v archivebox-data:/data archivebox /bin/archive 'https://example.com/'
[*] [2019-02-22 12:53:56] Downloading https://example.com/ > /data/sources/example.com-1550840036.txt
[*] [2019-02-22 12:53:57] Parsing new links from output/sources/example.com-1550840036.txt...
    > Adding 1 new links to index from /data/sources/example.com-1550840036.txt (parsed as Plain Text format)
[*] [2019-02-22 12:53:57] Updating main index files...
    > /data/index.json
    > /data/index.html
[▶] [2019-02-22 12:53:57] Updating content for 1 pages in archive...
[+] [2019-02-22 12:53:57] "http://www.iana.org/domains/example"
    http://www.iana.org/domains/example
    > /data/archive/1550840037 (new)
      > favicon
      > title
      > wget
      > pdf
      > screenshot
      > dom
      > archive_org
      > git
      > media
      √ index.json
      √ index.html
[√] [2019-02-22 12:54:17] Update of 1 pages complete (20.14 sec)
    - 1 entries skipped
    - 8 entries updated
    - 0 errors
    To view your archive, open: /data/index.html
[*] [2019-02-22 12:54:17] Updating main index files...
    > /data/index.json
    > /data/index.html
```

Where can i see the results now and the files? Maybe some information could be added about this in the docker section of the wiki ?

**Comment by flip111** [comment]
I did a

```
sudo mount --bind /var/lib/docker/volumes/archivebox-data/_data /mnt/
```

and then checked the mnt directory. I saw an index.html file there which looked like:

![screenshot archived sites](https://user-images.githubusercontent.com/2244480/53246912-e02e1480-36a9-11e9-9de9-74f688990b7c.png)

The saved link is like https://www.iana.org/domains/reserved
but i expected http://example.com/

I'm not sure if this is the right way to do it .. maybe i shouldn't use mount.

**Comment by pirate** [comment]
Hey this is correct, you did the right thing.

The reason it added `http://iana.org/domains/reserved` instead of `http://example.com` is because you passed the URL as an argument to `/bin/archivebox` instead of via stdin.

You can see on the https://github.com/pirate/ArchiveBox/wiki/Usage page, passing URLs via stdin archives each URL, but passing as the first argument treats it as a feed to scrape URLs from, so it's usually used for RSS feeds or netscape-format bookmark lists.  If you want to archive http://example.com, just pass it in via stdin instead of as an argument.

**Comment by flip111** [comment]
The usage page explains it well ... i overlooked this though. The stdin approach is not too intuitive without the description on the usage page, but ok.

Maybe some information can be added to the docker wiki page on how to view the results?

I will close this now because my initial issue has been resolved.

**Comment by pirate** [comment]
I just edited both the [[Docker]] and [[Usage]] pages to make it clearer, thanks!
