### ISSUE TITLE
Failed to archive link: KeyError: 'base_url'

### ISSUE THREAD

**Issue by sbrl** [pirate/ArchiveBox#161]
### Describe the bug
A description of what the bug is, what you expected to happen, 
and any relevant context about issue.

I've noticed that if I archive any website with v0.2.4, I get a blank page. That is to say that the generated `index.html` is blank. It generates a KeyError, as shown in the logs at the bottom of this report.

Here are the scripts I use to archive:

#### `archive-custom`
```bash
#!/usr/bin/env bash

export FETCH_MEDIA=true;
export FETCH_SCREENSHOT=false;
export FETCH_PDF=false;
export FETCH_DOM=false;
export RESOLUTION="1920x1080"; # Only used for screenshots
export OUTPUT_PERMISSIONS=644;


# Hide the fact that we're wget - unfortunately we get blocked by some sites for this - even though our use-case is legit
# Commented out by default, as ArchiveBox has a default user-agent string based on this now :D
# https://github.com/pirate/ArchiveBox/issues/39#issuecomment-454201125
if [ ! -z "${HIDE_UA}" ]; then
	export WGET_USER_AGENT="ArchiveBox/$(git rev-parse HEAD | head -c7) (+https://github.com/pirate/ArchiveBox/)";
fi

if [ ! -z "${HIDE_UA_SUPERSTEALTH}" ]; then
	export WGET_USER_AGENT="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0";
fi

./archive $@
```

#### `archive-url`
```bash
#!/usr/bin/env bash
export ONLY_NEW=true;
echo $1 | ./archive-custom
```

### Steps to reproduce
1. Enter `./archive-url 'https://arstechnica.com/information-technology/2014/02/how-to-run-your-own-e-mail-server-with-your-own-domain-part-1/'`
2. See error

### Screenshots or log output
If applicable, use screenshots or copy/pasted terminal output to help explain your problem.

```
$ ./archive-url 'https://arstechnica.com/information-technology/2014/02/how-to-run-your-own-e-mail-server-with-your-own-domain-part-1/'
[*] [2019-03-05 23:14:56] Parsing new links from output/sources/stdin-1551827696.txt...
    > Adding 1 new links to index (parsed import as Plain Text)
[*] [2019-03-05 23:14:56] Updating main index files...
    > output/index.json
    > output/index.html
[▶] [2019-03-05 23:14:56] Updating content for 1 pages in archive...
[+] [2019-03-05 23:14:59] "https://arstechnica.com/information-technology/2014/02/how-to-run-your-own-e-mail-server-with-your-own-domain-part-1/"
    https://arstechnica.com/information-technology/2014/02/how-to-run-your-own-e-mail-server-with-your-own-domain-part-1/
    > output/archive/1551827696 (new)
      > favicon
      > title                                                                   
      > wget                                                                    
      > archive_org                                                             
      > git                                                                     
      > media
      √ index.json                                                              
      √ index.html
    ! Failed to archive link: KeyError: 'base_url'
[√] [2019-03-05 23:15:31] Update of 1 pages complete (34.66 sec)
    - 1 entries skipped
    - 5 entries updated
    - 0 errors
    To view your archive, open: output/index.html
[*] [2019-03-05 23:15:31] Updating main index files...
    > output/index.json
    > output/index.html
```

### Software versions
(please complete the following information)

 - OS: Raspbian GNU/Linux 9.8 (stretch)
 - ArchiveBox version: `63e6ed8`
 - Docker version: Not installed
 - Python version: `Python 3.5.3`
 - Chrome version: Not installed
 - Wget version: `1.18`

<details>
<summary>Full <code>wget --version</code> output</summary>
<pre><code>
GNU Wget 1.18 built on linux-gnueabihf.

-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls 
+ntlm +opie +psl +ssl/gnutls 

Wgetrc: 
    /etc/wgetrc (system)
Locale: 
    /usr/share/locale 
Compile: 
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc" 
    -DLOCALEDIR="/usr/share/locale" -I. -I../../src -I../lib 
    -I../../lib -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/include 
    -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG -g -O2 
    -fdebug-prefix-map=/build/wget-3pRUTa/wget-1.18=. 
    -fstack-protector-strong -Wformat -Werror=format-security 
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall 
Link: 
    gcc -I/usr/include/p11-kit-1 -DHAVE_LIBGNUTLS -DNDEBUG -g -O2 
    -fdebug-prefix-map=/build/wget-3pRUTa/wget-1.18=. 
    -fstack-protector-strong -Wformat -Werror=format-security 
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall -Wl,-z,relro -Wl,-z,now 
    -L/usr/lib -lpcre -luuid -lnettle -lgnutls -lz -lpsl -lidn 
    ftp-opie.o gnutls.o http-ntlm.o ../lib/libgnu.a 

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
</code></pre>
</details>

**Comment by pirate** [comment]
Hey @sbrl thanks for reporting this.  I think this issue has already been fixed a few commits after the version you have.  Do you mind pulling the latest master and giving it a shot?

**Comment by sbrl** [comment]
Cool, thanks! It looks like it's fixed - and the other bug I was going to report whereby some oft he automatically generated links have been fixed too.

Excellent work :smiley_cat:
