### ISSUE TITLE
Archive Interactive Site

### ISSUE THREAD

**Issue by diego898** [pirate/ArchiveBox#166]
### Describe the bug
I am trying to save a full working copy of the interactive site https://distill.pub/2019/activation-atlas/ but when I try `echo "https://distill.pub/2019/activation-atlas/" | ./archive` the resulting archive only preserves the text. Reading the documentation, the default should save everything.

**Comment by pirate** [comment]
It's quite a complex site to save, but it does show up properly in the PDF/Screenshot output in my test: 

<img width="1489" alt="Screen Shot 2019-03-11 at 4 12 58 AM" src="https://user-images.githubusercontent.com/511499/54109121-270f5000-43b4-11e9-8a02-064446264fdf.png">

As this is not specifically related to this site, but is a general problem with archiving complex, interactive content, I'm closing it in favor of more specific issues with individual archive methods.


You can track our progress improving a few pieces of interactive site archiving here:
 - https://github.com/pirate/ArchiveBox/issues/154
 - https://github.com/pirate/ArchiveBox/issues/130

**Comment by diego898** [comment]
@pirate thanks for the response - is it a goal/within-scope for this project to try and save a site as complex as that?

**Comment by pirate** [comment]
Yes @diego898, it's 100% in-scope.  We want to be able to save every website you can view online with perfect fidelity. It's a goal shared by many of the other tools as well, from Archive.org to Webrecorder.io, we all care about getting it right ;)

This is a good set of tests if you're interested in seeing which tools are able to archive interactive sites: http://acid.matkelly.com

**Comment by diego898** [comment]
hey @pirate - sorry I don't know much about this. How exactly do I "use" or "test" using those sets of tests? thanks!
