### ISSUE TITLE
purge fails with import error

### ISSUE THREAD

**Issue by ehainry** [pirate/ArchiveBox#168]
### Describe the bug

Purge fails with an `ImportError`. It tries to import `parse_json_link_index` which fails.

```bash
$ ./bin/archivebox-purge
Traceback (most recent call last):
  File "./bin/archivebox-purge", line 9, in <module>
    from archive import parse_json_link_index
ImportError: cannot import name 'parse_json_link_index'
```

**Comment by Mortuus-Medicus** [comment]
Would it be possible to have a remove button/checkbox on the index.html, and thus you could remove by selecting them through that, it could then direcly remove the website or it could just mark it for when ./archive goes to write to it again, it sees the mark and moves the website.

**Comment by mlazana** [comment]
I'll work on it

**Comment by pirate** [comment]
@Mortuus-Medicus yes that will be added once we have the Django UI pushed.  For now that's impossible with static HTML as there's no server that's running to listen for the remove request.

The purge script will be updated in [v0.3.0](https://github.com/pirate/ArchiveBox/pull/197), can you wait until that version is released, or do you need to purge URLs immediately?

**Comment by Mortuus-Medicus** [comment]
@pirate Would it not be possible to achieve the same result with JS? Or is that not robust enough?

**Comment by pirate** [comment]
What do you mean? Client-side JS cannot access the filesystem, and we're not adding a node server just for that one feature when Django is almost finished anyway.

**Comment by Mortuus-Medicus** [comment]
I see, then there's no real point in reinventing the wheel if you already have almost finished Django!
(Hmm... Don't know why, but I'm feeling the urge to recreate your program in Go)

**Comment by pirate** [comment]
FYI This is fixed here: https://github.com/pirate/ArchiveBox/wiki/Roadmap#-archivebox-remove

There's a posted example of the new behavior there too ^

You can check it out on the `django` branch, but don't run it on a big existing archive without backing it up somewhere first!
