### ISSUE TITLE
Add Archivebox to Docker Hub

### ISSUE THREAD

**Issue by chauffer** [pirate/ArchiveBox#169]
Type:

 - [x] Propose a brand new feature

**What is the problem that your feature request solves**
I can use the Docker image on my Kubernetes cluster without having to build and maintain it myself

**Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes**
Enable automatic image building on docker hub. https://docs.docker.com/docker-hub/builds/

**What hacks or alternative solutions have you tried to solve the problem?**
N/A

**How badly do you want this new feature?**
 - [x] It's an urgent deal-breaker, I cant live without it
 - [ ] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually
 - [ ] I'm willing to contribute to development

**Comment by pirate** [comment]
**Official Docker Hub image: https://hub.docker.com/r/nikisweeting/archivebox**

**Updated Docker docs:** https://github.com/pirate/ArchiveBox/wiki/Docker

Will also get it listed on https://github.com/docker-library/official-images in the near future.
