### ISSUE TITLE
pdf?

### ISSUE THREAD

**Issue by g-mc** [pirate/ArchiveBox#171]
https://github.com/pirate/ArchiveBox/blob/32c39d0fd062738b23cf8c45164996f1c4b467f0/archivebox/util.py#L368-L370

Is it necessary to have `'pdf'` in Line 370?

**Comment by pirate** [comment]
I'm removing `get_link_type` entirely in the next release, so this code will all dissapear.  It's only being used in one place anyway right now, and that can be refactored out with better use of `derived_link_info()`, but thanks anyway for the code review!

**Comment by g-mc** [comment]
No problem, thanks for the explanation! I’ve been enjoying reading through
the code just to try and understand how it all works!

Thanks for your time!
