### ISSUE TITLE
Running the program gets a 'CROME_USER_AGENT' error

### ISSUE THREAD

**Issue by TheChiefMeat** [pirate/ArchiveBox#182]
Running the program gets a 'CROME_USER_AGENT' error.

```
Traceback (most recent call last):
  File "./archive", line 15, in <module>
    from archive_methods import archive_link, _RESULTS_TOTALS
  File "/home/pi/radio/fm_transmitter-master/ArchiveBox/archivebox/archive_methods.py", line 12, in <module>
    from config import (
ImportError: cannot import name 'CHROME_USER_AGENT'
```
OS: Raspbian Jessie Lite
Python3 version: 3.5.3
Chrome version: Chromium 65.0.3325.181 Built on Raspbian , running on Raspbian 9.8
Wget version: GNU Wget 1.18

**Comment by n0ncetonic** [comment]
Sorry this is my fault on missing a file in my latest pull request. I'm issuing another pull request now.

For the time being feel free to add the following to `config.py`

```
CHROME_USER_AGENT =      os.getenv('CHROME_USER_AGENT',      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36')

```

Add that underneath `CHROME_HEADLESS`

**Comment by TheChiefMeat** [comment]
Thanks, that seems to have fixed it :)
