### ISSUE TITLE
Improper quoting of wget useragent flag

### ISSUE THREAD

**Issue by n0ncetonic** [pirate/ArchiveBox#190]
## Describe the bug
wget appears to have a slight typo in the command generation in specific in dealing with the `--user-agent` flag.

## Steps to reproduce
I observed the following when a page returned a 404 response (not a fault of ArchiveBox, the page was legitimately not found). Any method of running ArchiveBox that would display the generated output for commands would show this as well

## Screenshots or log output
 The wget command outputs the following as part of its run flags. 

`"--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"`.

Is this done intentionally or is the intended functionality to output `--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"` ?

## Software versions

 - OS:                       macOS 10.14
 - ArchiveBox version:        0075daa
 - Python version:            Python 3.7.2
 - Chrome version:           N/A

**Comment by n0ncetonic** [comment]
This appears to be replicated in the chrome flags as well

` /Applications/Chromium.app/Contents/MacOS/Chromium --headless --disable-web-security --ignore-certificate-errors "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36" --window-size=1440,900 --timeout=40000 "--user-data-dir=/Users/user/Library/Application Support/Chromium" --dump-dom https://url.com`

**Comment by pirate** [comment]
It's intentional and harmless.  That's only how it's printed for the user to copy, not actually how it's run.
