### ISSUE TITLE
Non-link-following archiving

### ISSUE THREAD

**Issue by diego898** [pirate/ArchiveBox#195]
(please fill out the following information, feel free to delete sections if they're not applicable)

## Describe the bug
While archiving this link:

https://gradientscience.org/batchnorm/

I realized it suddently started to try and archive youtube links, reddit links, github themes, etc. Previous blog posts Ive archived have not archived this way. How can I make it only archive the current page/url Ive passed?

## Steps to reproduce

`./archive https://gradientscience.org/batchnorm/`

## Software versions

 - OS: 10.14
 - ArchiveBox version: 58c9b47
 - Python version: 3.6.8

**Comment by pirate** [comment]
https://github.com/pirate/ArchiveBox/wiki/Usage#import-a-single-url-or-list-of-urls-via-stdin

https://github.com/pirate/ArchiveBox/wiki/Usage#import-list-of-links-exported-from-browser-or-another-service

Links piped in via stdin are added to the archive, URLs passed as an argument get treated like a feed of URLs to import, not an individual page.
