### ISSUE TITLE
Archive Method: Wget: unrecognized option '--compression=auto'

### ISSUE THREAD

**Issue by mawmawmawm** [pirate/ArchiveBox#196]
Hey there, I just pulled the master and poked around and then I realized that the wget command isn't working correctly. Running via docker-compose.

## Describe the bug
wget is being executed with the following standard parameters:

```
wget --no-verbose --adjust-extension --convert-links --force-directories --backup-converted --span-hosts --no-parent --compression=auto -e robots=off --restrict-file-names=unix --timeout=60 --warc-file=warc/1553663964 --page-requisites "--user-agent=ArchiveBox/58c9b47d4 (+https://github.com/pirate/ArchiveBox/) wget/1.18" https://www.theatlantic.com/health/archive/2014/05/why-medicine-is-cheaper-in-germany/371418/
```
If I run this outside of the script, I get a `wget: unrecognized option '--compression=auto'` which makes wget basically stopp working.

## Steps to reproduce

Run the above mentioned wget command

My workaround was to edit `archivebox/archive_methods.py` manually inside the container and comment out the `compression=auto` there.

**Comment by pirate** [comment]
This was just fixed, can you pull and try again.

**Comment by go2tom42** [comment]
I just pulled it and get the same error

`wget: unrecognized option '--compression=auto'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
[*] [2019-03-30 20:18:58] Parsing new links from output/sources/stdin-1553977138.txt...
    > Adding 0 new links to index (parsed import as Plain Text)
[*] [2019-03-30 20:18:58] Saving main index files...
    > /data/index.json
    √ /data/index.json
`

**Comment by pirate** [comment]
@go2tom42 strange, can you give me this info and I'll debug it:

- current git commit you're on
- the output of `wget --compression=auto --help` on your machine (specifically I need the status code, whether it's 0 or something else)
- if possible the output of this from python to `cd ArchiveBox;`:
```python
>>>from archivebox.config import WGET_AUTO_COMPRESSION
>>>print(WGET_AUTO_COMPRESSION)
True
```
```python
>>>from archivebox.util import run
>>>run(["wget", "--compression=auto", "--help"], stdout=DEVNULL).returncode
0
```

**Comment by go2tom42** [comment]
I'm using the image from https://hub.docker.com/r/nikisweeting/archivebox


Output from `wget --compression=auto --help` inside container


```
$ wget --compression=auto --help
wget: unrecognized option '--compression=auto'
Usage: wget [OPTION]... [URL]...

Try 'wget --help' for more options.
$
```

From location `home/pptruser/app/archivebox` ran python3 then
```
python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from .config import WGET_AUTO_COMPRESSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: Parent module '' not loaded, cannot perform relative import
```
`from .util import run` give same result as above



The wget inside the container is version 1.18, I believe compression was added with version 1.19.2 https://lists.gnu.org/archive/html/info-gnu/2017-10/msg00007.html

**Comment by bradparks** [comment]
I get this error as well

**Comment by pirate** [comment]
This should be fixed on the latest django branch. If you're still seeing any issues comment back here and I'll reopen the ticket.
```bash
git checkout django
git pull
docker build . -t archivebox
docker run -v $PWD/output:/data archivebox init
docker run -v $PWD/output:/data archivebox add 'https://example.com'
```
