### ISSUE TITLE
Fix config file sourcing in wiki

### ISSUE THREAD

**Issue by kylebarron** [pirate/ArchiveBox#198]
## Describe the bug
I don't know how to make a PR against the wiki, so I'm creating a bug report instead. To source the config file it should be
```
export $(grep -v '^#' ~/.ArchiveBox.conf | xargs); 
```
not 
```
export "$(grep -v '^#' ~/.ArchiveBox.conf | xargs)"; 
```

## Steps to reproduce

When I run 
```
export "$(grep -v '^#' ~/.ArchiveBox.conf | xargs)"; 
```
I get the whole configuration put into a single environment variable. When running `env` I get the following all in a single line.
```
OUTPUT_DIR=/home/kyle/sftp_sync/archive ONLY_NEW=False FETCH_TITLE=True FETCH_FAVICON=True FETCH_WGET=True FETCH_WARC=False FETCH_PDF=False FETCH_SCREENSHOT=False FETCH_DOM=True FETCH_GIT=False FETCH_MEDIA=False SUBMIT_ARCHIVE_DOT_ORG=False
```
`archive` then used everything after `OUTPUT_DIR=` for the output directory.

Instead, without the quotes around `grep` means that the config is split correctly.

I'm using Zsh.

## Software versions

 - OS: Ubuntu 18.04
 - ArchiveBox version: e797a7a
 - Python version: 3.7.1

**Comment by pirate** [comment]
You're right, thanks, just fixed it fixed now.
