### ISSUE TITLE
Add support for scdl as a SoundCloud download backend

### ISSUE THREAD

**Issue by khimaros** [pirate/ArchiveBox#205]
## Type 

 - [X] Propose a brand new feature
 - [X] Request modification of existing behavior or design

## What is the problem that your feature request solves

youtube-dl seems to be a bit finicky with SoundCloud download links compared to scdl.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

New configuration option `FETCH_SCDL` to enable fetching via scdl instead of youtube-dl.

## What hacks or alternative solutions have you tried to solve the problem?

Use youtube-dl.

## How badly do you want this new feature?

 - [X] It would be nice to have eventually

---

 - [X] I'm willing to contribute to development / fixing this issue
 - [X] I like ArchiveBox so far / would recommend it to a friend

**Comment by khimaros** [comment]
Feel free to close, it seems like the latest version of youtube-dl from pip has solved my flakiness problems.

**Comment by pirate** [comment]
Yeah, I think youtube-dl is broken and fixed quite frequently, sites often change their HTML/CSS/JS and it takes the community few days to push fixes.

In the pursuit of simplicity, I think I'm going to close this for now, as I anticipate user-provided puppeteer scripts will be able to beat both youtube-dl and scdl once released: #51.

Thanks for the nice ticket and suggestion though!
