### ISSUE TITLE
Check page status (up/down) and don't attempt archiving on inaccessible pages

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#209]
On every pass through, perform a simple GET request to check if the server is responsive, and save the response code in the archive json.

If the code is >400, don't attempt running archive methods as they will only save broken 404 pages.

Related to: https://github.com/pirate/ArchiveBox/pull/203
CC: @shakkhar

I'm just saving this issue to make sure I don't forget to add this to the next release.

**Comment by cdvv7788** [comment]
A `HEAD` request may be enough for this (fulfills the purpose while being lighter)

**Comment by cdvv7788** [comment]
The conclusion about this is that it is better to spend some additional time trying to archive the URL, even if it only works with a single method than adding checks for accessibility. Those can get complicated (SSL handshakes, HTTP response codes, HTTP methods, etc).
In short, it currently works as expected. Every archive method will be ran against the url without any previous sanity checks.

**Comment by pirate** [comment]
If there are enough complaints maybe we can make this an option in the future, but I think for now as @cdvv7788 said it's better to try a down URL few unnecessary times than to potentially miss archiving it because it only responds to certain types of requests in certain situations.
