### ISSUE TITLE
Can't write wget snapshots of URL with query-string

### ISSUE THREAD

**Issue by bltavares** [pirate/ArchiveBox#210]
## Describe the bug
Most of Linux filesystems allow to use `?` and other special characters as part of folder and filenames. But if you run this using ExFAT as the storage, it will throw the following error:

```
Got wget response code 3:
Cannot write to ‘www.youtube.com/watch?v=BkW1xQgrSPQ.html’ (No such file or directory).
```

ExFAT are common filesystems for portable USB drives, specially if there is the intention to use it with Linux, Windows and MacOS. It is not the best archival filesystem (eg: zfs), but it is the most portable filesystem.

I'm not sure how to do that yet, but it would be nice to convert special characters into safer ones when writing it down to the disk.

## Steps to reproduce

1. Create a ExFAT partition, `cd` into it
2. Execute archivebox using a YouTube URL: `echo 'www.youtube.com/watch?v=BkW1xQgrSPQ' | ./archive`

## Software versions

 - OS:                       Debian
 - ArchiveBox version:       docker image: `296aa767078f`

**Comment by pirate** [comment]
Hmm interesting, looks like we'll have to switch from `--restrict-file-names=unix` to `--restrict-file-names=windows` now that we support Windows and Windows file systems.  When set to `windows`, wget's filename escaping is a superset of the escaping that `unix` does, so it'll continue to work on existing systems but make all newly archived files ExFAT/NTFS compatible.

https://www.gnu.org/software/wget/manual/wget.html#targetText=--restrict-file-names=modes

**Comment by pirate** [comment]
Done https://github.com/pirate/ArchiveBox/commit/4f599c0b0b07c842b1a2d0ec31f229d8fa0d6294

**Comment by bltavares** [comment]
Thank you! 🙇

**Comment by bltavares** [comment]
@pirate I've tried the latest Docker image published, which should include the fix, but it still reports as Unix on the error log.

Looking at the code, it might not be enough to only add the flag, as it might need to adjust the `wget_output_path` might need to change as well.

**Comment by bltavares** [comment]
I've noticed that the Dockerfile clones the latest commit on Github, instead of copying the project with their changes into the image. This could cause some confusion on why a change is not being built.

I'll send a PR soon :)
