### ISSUE TITLE
Use eval to source environment variable

### ISSUE THREAD

**Issue by fr0der1c** [pirate/ArchiveBox#215]
## Wiki Page URL
https://github.com/pirate/ArchiveBox/wiki/Configuration#creating-a-config-file

## Suggested Edit
change
```
export $(grep -v '^#' ~/.ArchiveBox.conf | xargs); ./archive https://example.com/rss/feed.xml
```
to
```
eval export $(grep -v '^#' ArchiveBox.conf); ./archive https://example.com/rss/feed.xml
```

The original one doesn't work if there are whitespaces in value, even if the value has been quoted. I found this problem when setting Chrome user profile directory. I'm not a shell hacker but seems the `$()` subcommand is misinterpreting whitespace and `eval` solves the problem.

**Comment by pirate** [comment]
Thanks, fixed!
