### ISSUE TITLE
Use of color in output makes finding errors difficult

### ISSUE THREAD

**Issue by paulehoffman** [pirate/ArchiveBox#218]
I was running ./archive as root, which was probably a bad idea anyway. However, it could not figure out why PDFs and so on were not being kept because the useful part of the error messages was in yellow. Not all of us use "dark mode", which made the error nearly impossible to see.
Proposal: use color more sparingly in error messages, or only use colors that appear well on both dark and light backgrounds.
(And, yes, I am now running just fine once I created a non-root user. I'm quite excited by this program!)

**Comment by pirate** [comment]
[`USE_COLOR=False`](https://github.com/pirate/ArchiveBox/wiki/Configuration#use_color)

I can change it to something other than yellow but I recommend setting up your terminal config so that all standard ANSI colors are visible.
