### ISSUE TITLE
Create an archivebox server page with a UI & REST API endpoint to add links to the archive

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#221]
### Page Requirements

 - [ ] ability to add a single page to the archive (like `echo <url> | archivebox add`)
 - [ ] ability to import a list of pages / feed of URLs into the archive (like ` archivebox add <url>`)
 - [X] link to the homepage of the index `/`
 - [X] link to the django admin list of URLs for editing the archive `/admin/`
 - [X] link to the archivebox github repo & documentation

<img src="https://user-images.githubusercontent.com/511499/56526534-66d06800-651a-11e9-9868-8c5cf01c5d92.JPG" width="400px">

### Setup

To set up your dev environment, run the following:

```bash
pip3 install --upgrade pip setuptools virtualenv pipenv

cd ~/path/to/ArchiveBox
git checkout django
git pull

pipenv install
pip install -e
```

Then to create a new collection and run the server, do:
```bash
mkdir data
cd data/
archivebox init
archivebox add https://example.com
archivebox info

archivebox server
# then open: http://127.0.0.1:8000
```

To edit the templates you can change files in:
 - `archivebox/themes`
 - `archivebox/legacy/templates`

**Comment by pirate** [comment]
CC: @mlazana

**Comment by pirate** [comment]
This is planned for v0.5. There is already an admin UI for editing and removing existing links in v0.4, so v0.5 will add the ability to submit new links via UI as well.

**Comment by pirate** [comment]
This is done and available on the latest `django` branch (soon to be master).
```bash
git checkout django
git pull
docker build . -t archivebox
docker run -v $PWD/output:/data archivebox init
docker run -v $PWD/output:/data archivebox add 'https://example.com' --only-new
```

**Comment by dgtlmoon** [comment]
+1 here, would love to trigger it from https://github.com/dgtlmoon/changedetection.io

**Comment by pirate** [comment]
this is a very old issue @dgtlmoon 😄 ! if you're looking for a UI page we've already had one for several versions now, if you're looking for a REST API endpoint to add links, you can just POST to `/core/snapshot/add/` (using `archivebox:dev`) and find more info here: 

- https://github.com/ArchiveBox/ArchiveBox/issues/496
- https://github.com/ArchiveBox/ArchiveBox/issues/577#issuecomment-872640967
