### ISSUE TITLE
doc for config file

### ISSUE THREAD

**Issue by HappyDoggo** [pirate/ArchiveBox#222]
## Wiki Page URL
https://github.com/pirate/ArchiveBox/wiki/Configuration#creating-a-config-file

## Suggested Edit
`eval export $(grep -v '^#' ArchiveBox.conf); ./archive https://example.com/rss/feed.xml`

In the case that it causes an error message: `grep: .ArchiveBox.conf: No such file or directory`

Run:
`find ~/.ArchiveBox.conf`
Copy the printed path.
`eval export $(grep -v '^#' <insert path here>); ./archive https://example.com/rss/feed.xml`

**Comment by pirate** [comment]
Done, thanks.
