### ISSUE TITLE
ArchiveBox incorrectly identifies input source

### ISSUE THREAD

**Issue by pigmonkey** [pirate/ArchiveBox#228]
I always call ArchiveBox with a path to a Pinboard JSON file as an argument.

    $ ./archive ~/library/conf/pinboard.json

From the terminal this works fine. However, when this is called by a systemd service (which is executed by a systemd timer), it fails:

    Parsing new links from output/sources/stdin-1556669507.txt...
    [X] No links found :(

The problem is the `if not sys.stdin.isatty()` conditional in `bin/archivebox`. When called via systemd, `isatty()` will return `False`, which causes ArchiveBox to assume that it should look to `stdin` for input (despite correctly identifying the input argument a few lines previously in the `if len(args) == 2:` check).

There should be another check to see if `stdin` is empty.

**Comment by pirate** [comment]
Thanks, this is all refactored in [v0.4.0](https://github.com/pirate/ArchiveBox/pull/207) as well.
