### ISSUE TITLE
Add SingleFile in the list of existing tools

### ISSUE THREAD

**Issue by gildas-lormeau** [pirate/ArchiveBox#230]
## Wiki Page URL
https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community

## Suggested Edit
Add SingleFile in the list of existing tools, cf. https://github.com/gildas-lormeau/SingleFile/. This extension exists now for more than 9 years and can also be run as a standalone script from the command line.

**Comment by pirate** [comment]
Done 👍

**Comment by gildas-lormeau** [comment]
Thanks!
