### ISSUE TITLE
Docs: The demo site is returning a 502 Bad Gateway Error

### ISSUE THREAD

**Issue by mcat-ee** [pirate/ArchiveBox#231]
#### Describe the bug
[See title](https://archive.sweeting.me/)

**Comment by pirate** [comment]
Yaaaah I know, I'm still in the process of moving my home server from NY to MTL and my archive data is still sitting on a hard drive in my room.  I'll finish setting it up at some point...

**Comment by digitalsignalperson** [comment]
The demo site presents a login page. Was trying to guess the username password (demo/demo?). Is it still out of order?

**Comment by pirate** [comment]
Ok it's sort of up but not really working properly https://archive.sweeting.me

**Comment by pirate** [comment]
It's up

**Comment by whalehub** [comment]
@pirate The current demo domain (https://archivebox.zervice.io/) doesn't have an A record associated with it so it's currently inaccessible.

**Comment by pirate** [comment]
It doesn't use A-records, it uses automatically provisioned CNAME & SSL records when the cloudflare argo tunnel is active. When I do server maintenance it goes offline and automatically comes up later after reboots and such. It should be up now but in general I'd only expect ~90% uptime from that server as I use is as my scratchbox for tons of other projects.

**Comment by kerim** [comment]
Demo site is down. Server Error (500).

**Comment by pirate** [comment]
Yeah there's a power outage at my house right now that's outlasting our UPS batteries.

**Comment by kerim** [comment]
Now it says:

Error 1033 Ray ID: 668338d4dc6b31fd • 2021-07-01 22:55:27 UTC
Argo Tunnel error

**Comment by pirate** [comment]
Yes, I will fix it eventually, no need to post here when it goes down. I have my own monitoring and it's not a 100% uptime guarantee service, it's my personal home server and lives and dies at my whims.

**Comment by kerim** [comment]
From my perspective it was never up in the first place. I got a note from you that seemed to suggest it had been fixed so I checked it out only to see it was still down. Sorry if you found this annoying, but I was trying to share information about this service (which I just learned about) with other people and, and it is hard to do that if there is no working demo.

**Comment by pirate** [comment]
No worries, thank you for posting and sorry for the cranky tone, I'm mostly commenting so future ppl coming to the ticket see it. I understand a working demo is important, but in the grand scheme of things I'm ok losing a few potential users in exchange for the convenience, flexibility, and cheap storage/power costs of keeping the demo on my home server.
