### ISSUE TITLE
Chromium installed but not found by `./archive`

### ISSUE THREAD

**Issue by Duponin** [pirate/ArchiveBox#242]
#### Describe the bug

`./archive` don't find `chromium-browser` even if it's installed.

#### Steps to reproduce

1.  `pkg install chromium` (successful installation)
2. `./archive`

#### Screenshots or log output

`[X] Missing dependency: chromium-browser`

#### How I fixed it

I did a simple symbolic linck because it was looking for the wrong binary.

`ln -s /usr/local/bin/chrome /usr/local/bin/chromium-browser`

#### Software versions

 - OS: FreeBSD 12.0
 - ArchiveBox version: de28748
 - Python version: 3.6.8
 - Chrome version: Chromium 73.0.3683.103

#### Sidenote

It should be easily fixed. If I enjoy that tool and have some free time, I'll try to PR the installer to support FreeBSD.

**Comment by pirate** [comment]
It tries all of these in order, so if it's not able to find it then it's probably not in your `PATH`:

```python
        default_executable_paths = (
            'chromium-browser',
            'chromium',
            '/Applications/Chromium.app/Contents/MacOS/Chromium',
            'google-chrome',
            '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
            'google-chrome-stable',
            'google-chrome-beta',
            'google-chrome-canary',
            '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
            'google-chrome-unstable',
            'google-chrome-dev',
        )
```

What's the output of running `chromium --version` in the same shell that you run ArchiveBox in?

**Comment by Duponin** [comment]
Hi,

For chrome:
```
root@archive-box:~ # which chromium && chromium --version
chromium: Command not found.
```

For chromium-browser:
```
root@archive-box:~ # which chromium-browser && chromium-browser --version 
/usr/local/bin/chromium-browser
Chromium 73.0.3683.103 
```

It works because I did a logical link to fix it:
```
root@archive-box:~ # ls -l /usr/local/bin/chromium-browser 
lrwxr-xr-x  1 root  wheel  21 May 19 00:25 /usr/local/bin/chromium-browser -> /usr/local/bin/chrome
```

To add `chrome` or `/usr/local/bin/chrome` to `default_executable_paths` could the way to fix.

**Comment by pirate** [comment]
Just fixed this on `master`: https://github.com/pirate/ArchiveBox/commit/e2b714ba95b26646b6d671576f343f1b9768189c

Pull the latest version and comment back if you have any problems and I'll reopen the ticket.
