### ISSUE TITLE
Claim your name on PyPI

### ISSUE THREAD

**Issue by Julian** [pirate/ArchiveBox#252]
It looks like you have plans to [support package manager installation](https://github.com/pirate/ArchiveBox/wiki/Roadmap) which is great!

You should probably claim the name ["archivebox" on PyPI](https://pypi.org/project/archivebox/) immediately, even if that isn't yet done, otherwise someone may swoop in and register it between now and whenever you do support installation that way.

**Comment by pirate** [comment]
Already have a while ago :wink: 
<img src="https://user-images.githubusercontent.com/511499/60697560-ee423c00-9eb8-11e9-9d38-3359b076b1c6.png" width="600px">
