### ISSUE TITLE
Delete tagged archived site

### ISSUE THREAD

**Issue by PietroMB** [pirate/ArchiveBox#261]
Add the "button" delete all archived post by specific tag pls

**Comment by pirate** [comment]
I can allow the CLI to filter by other columns with something like `--column=tags` https://github.com/pirate/ArchiveBox/wiki/Roadmap#-archivebox-remove.

It can also be added as a filter in the Django Admin which would allow for deletion too.

**Comment by cdvv7788** [comment]
We are reviewing a better implementation for tags. Once that is done, this should be easier.

**Comment by cdvv7788** [comment]
@pirate LGTM. Can you give this a check please?

**Comment by pirate** [comment]
This is complete, you can now filter by tag in the UI by using the filter options on the right, then select all using the checkboxes and click "delete". Or you can use the cli using the new `archivebox remove --filter-type=tag abc` option.

These features are on `master` currently and will be available in the next release.
