### ISSUE TITLE
don't enforce SSL verification or prompt user to proceed with download

### ISSUE THREAD

**Issue by LaserWires** [pirate/ArchiveBox#262]
There are many sites which have issues with SSL certifications some of them are also temperary issues. It would be ideal to permit users to download sites which have issues with SSL certifications. Currently ArchiveBox presents user with this error message shortly after aborting the request to download a site.

> $ ./archive https://www.site-with-ssl-issue.com
> [*] [2019-09-05 04:18:59] Downloading https://site-with-ssl-issue.com
> [!] Failed to download https://site-with-ssl-issue.com                                                                                                                                 
> 
>      <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>

A resolution to this is simply to issue a command switch to disable SSL verification for the entire download batch since the batch will likely contain a plurality of sites with SSL issues.

**Comment by pirate** [comment]
https://github.com/pirate/ArchiveBox/wiki/Configuration#check_ssl_validity

**Comment by LaserWires** [comment]
Nice config file seemingly undocumented.

**Comment by LaserWires** [comment]
It still outputs error. config file http://dpaste.com/3S8BKPZ
