### ISSUE TITLE
Bugfix: ArchiveBox ignoring config values via environment variable and ArchiveBox.conf

### ISSUE THREAD

**Issue by LaserWires** [pirate/ArchiveBox#263]
Downloading sites without enforcing SSL verification doesen't function

>  CHECK_SSL_VALIDITY=false

does not permit user to download from site with outdated or incorrectly setup certificates.

> [!] Failed to download https://site-with-ssl-issue.com                                                          
>      <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>

[ArchiveBox.conf.default.txt](https://github.com/pirate/ArchiveBox/files/3587144/ArchiveBox.conf.default.txt)

Aliasing in ~/.bashrc did not resolve the issue with ArchiveBox SSL verification.

> alias wget='wget --no-check-certificate'
> alias curl='curl -k'

**Comment by LaserWires** [comment]
Issue resolved, needs to be in proper directory.

**Comment by LaserWires** [comment]
CHECK_SSL_VALIDITY malfunctions regardless of file location.

It only downloads sites with SSL issues when line in **archivebox/config.py**

> CHECK_SSL_VALIDITY =     os.getenv('CHECK_SSL_VALIDITY',     'False'             ).lower() == 'False'

is modified

**Comment by pirate** [comment]
Can you verify that the environment variable is actually making it to archivebox by adding a line that line to print:
```python3
print('CHECK_SSL_VALIDITY=', os.getenv('CHECK_SSL_VALIDITY', 'UNSET'))
```
Or by running `archivebox config --get=CHECK_SSL_VALIDITY`.

**Comment by LaserWires** [comment]
Outputs **CHECK_SSL_VALIDITY= UNSET**

This is likely identical culprit to bug https://github.com/pirate/ArchiveBox/issues/268

**Comment by pirate** [comment]
Going to close the other issue and rename this one, since it seems to be a generic issue with config handling.

**Comment by pirate** [comment]
Do you mind posting your archivebox version, and the exact command you're using to run archivebox.  Also the output of `archivebox --version`.

**Comment by LaserWires** [comment]
$ ./archive version
ArchiveBox version b7ea44a1e

Config files are identical
**~/.ArchiveBox.conf**
**ArchiveBox/etc/ArchiveBox.conf.default**

**Comment by LaserWires** [comment]
From git 

`git clone https://github.com/pirate/ArchiveBox`

```
$ ./archive version
ArchiveBox version b7ea44a1e
```

Config files are identical
```
~/.ArchiveBox.conf
ArchiveBox/etc/ArchiveBox.conf.default
```
To archive
./archive http://www.site-to-archive.com

**Comment by pirate** [comment]
Ah I thought you were running the v0.4 branch.  The current version on master actually doesn't support config files at all, it's all done via environment variables, so you'd have to source your config file before running the command manually.
```bash
source ~/.ArchiveBox.conf
echo $CHECK_SSL_VALIDITY
./archive http://www.site-to-archive.com
```
Can you confirm that that outputs `false` before archivebox starts.

**Comment by LaserWires** [comment]
It used to archive sites with ssl issues fine if **CHECK_SSL_VALIDITY** was manually exported but the media option doesn't work regardless if its both exported manually and in both config files.

```
$ source ~/.ArchiveBox.conf 
$ echo $CHECK_SSL_VALIDITY
False
```

**Comment by LaserWires** [comment]
There is no issue any longer, setting enviorment variables works really well including for disabling media downloads.
