### ISSUE TITLE
Mobile Support?

### ISSUE THREAD

**Issue by kerim** [pirate/ArchiveBox#267]
## Type 

 - [x] General Question or discussion
 - [ ] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## What is the problem that your feature request solves

I am considering using this software but couldn't find information about whether or not it can sync with my iPhone.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Offline access to recent articles on my iPhone

## How badly do you want this new feature?

 - [x] It's an urgent deal-breaker, I cant live without it
 - [ ] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ ] I'm willing to contribute to development / fixing this issue
 - [ ] I like ArchiveBox so far / would recommend it to a friend

**Comment by pirate** [comment]
What exactly are you trying to accomplish?  Adding links from your phone, or viewing the archive on your phone, or saving the actual archive data on your phone?

**Comment by kerim** [comment]
Hmmm. I think I misunderstood what this application does. I saw it listed somewhere as a self-hosted alternative to Instapaper, but that does not seem to be the case.

**Comment by pirate** [comment]
It sort of is in some ways, it integrates with services like Instapaper to provide archiving functionality like Pinboard Premium/Pocket Premium, but it can also be used to replace them entirely depending on how you set it up.  The most common use is importing list of links from Bookmarks / Browsing History / or a bookmarking service like Instapaper, then piping it into ArchivBox to get an offline-browsable archive.

**Comment by kerim** [comment]
I see. Thanks.
