### ISSUE TITLE
Downloads multimedia content regardless of configuration

### ISSUE THREAD

**Issue by LaserWires** [pirate/ArchiveBox#268]
Archivebox will download youtube content regardless if 

```
FETCH_DOM
FETCH_MEDIA
```
are set to false in **ArchiveBox.conf** this was further verified by manually setting the environment variable with

```
$ export FETCH_DOM=false
$ export FETCH_MEDIA=false
```
then verified with
`$ env`
this being a legitimate archivebox bug.

**Comment by pirate** [comment]
See https://github.com/pirate/ArchiveBox/issues/263
