### ISSUE TITLE
Feature Request: Implement non ambiguous config parameters

### ISSUE THREAD

**Issue by LaserWires** [pirate/ArchiveBox#269]
Currently the config **etc/ArchiveBox.conf.default** doesn't have well defined parameters for multimedia content

This requires  
`#FETCH_MEDIA`

to be made less ambiguous because images, flash objects, java objects and videos are all multimedia some maybe desirable while others might not be which would only prolong the archiving operation and decrease disk storage capacity.

**Comment by pirate** [comment]
FETCH_MEDIA is currently strictly for enabling/disabled `youtube-dl`, which downloads audio and video, toggling has no effect on flash/images/java/etc.  All the `FETCH_` config keys are already going to be deprecated in v0.4.5 in favor of more granular settings.
