### ISSUE TITLE
Feature Request: Permit users to specify link depth for archiving

### ISSUE THREAD

**Issue by LaserWires** [pirate/ArchiveBox#270]
It would be ideal to permit users to define to which depth an archive operation would span. This is a common feature in website mirroring apps in which a user specifies the link depth from a URI the app will download. With no value specified it should only download the specific URI and only content from the passed URI and archive no other link in it.

**Comment by pirate** [comment]
Duplicate: https://github.com/pirate/ArchiveBox/issues/191
