### ISSUE TITLE
Feature Request: Archive only from specific domain  

### ISSUE THREAD

**Issue by LaserWires** [pirate/ArchiveBox#271]
It would be ideal to permit users to archive from a specific domain thus preventing archivebox from archiving pages from any other domain than from the URI which it was given. This should not interfere with multimedia objects such as videos as those are typically hosted by other domains other than the URI passed to archivebox.

**Comment by pirate** [comment]
You can pull this off using the https://github.com/pirate/ArchiveBox/wiki/Configuration#url_blacklist feature.

Archiving pages on one domain but media on any domain is not as simple as it sounds, there are potentially dozens of possible behaviors around how edge cases are handled, but if you can express exactly the behavior you want in regex form, `URL_BLACKLIST` should work fine.
