### ISSUE TITLE
Question: ...Tagging and removing

### ISSUE THREAD

**Issue by arnauldb** [pirate/ArchiveBox#279]
Hello,

I am very happy with Archivebox. I am using it at home to archive interesting sites and plan to set it up on a raspberry pi with an attached hdd for my personal archives. 

Is there a way to tag when I run : 

`echo 'https://stephenjones.blog/houshan-daoists/' | env OUTPUT_DIR="/media/arnauld/DATA/archivbox" ONLY_NEW=True ./archive`

Also, how can I remove a link which is archived locally?

Thank you.

**Comment by dataarchivist** [comment]
As far as I understand, simply delete the folder you dont want, in the output folder?

**Comment by arnauldb** [comment]
Thank you @dataarchivist , I was expecting something like a command to erase an archived site...

**Comment by dataarchivist** [comment]
> 
> 
> Thank you @dataarchivist , I was expecting something like a command to erase an archived site...

Shure you can rm it, but due the fact that we have an index, its mostly not just a command. 
I think its its easier in the great next update.

**Comment by pirate** [comment]
Removal command is already present in v0.4, see here for usage: https://github.com/pirate/ArchiveBox/wiki/Roadmap#-archivebox-remove

You can check it out early to beta test it but the official public release is still pending. Follow this PR for progress updates https://github.com/pirate/ArchiveBox/pull/207
