### ISSUE TITLE
Link Parsing: Add support for OneTab bookmark exports

### ISSUE THREAD

**Issue by compliment** [pirate/ArchiveBox#28]
https://www.one-tab.com/

**Comment by pirate** [comment]
Onetab exports are super simple, just a list of URLS and titles.  Unfortunately they don't have timestamps, so we'll have to make some up or come up with a different uuid for each archive (hash of the url maybe?).

Sample:
```
http://yelouafi.github.io/redux-saga/docs/recipes/index.html | Recipes | redux-saga
http://grater.sweeting.me:3000/channel/general | Rocket.Chat
http://grater.sweeting.me:3000/channel/general | Rocket.Chat
http://grater.sweeting.me:3000/channel/general | Rocket.Chat
https://grater.l/ | Home | Grater
https://fonts.google.com/?selection.family=Playfair+Display | Google Fonts
```

**Comment by compliment** [comment]
Yeah, and one-tab shared urls like [this one](https://www.one-tab.com/page/q25wyJ0MQDKVVSgwLOtdjg)

**Comment by pirate** [comment]
wget had a bug in a recent version that stopped it from resolving a ton of totally valid urls, upgrading it to 1.9.1_1 fixed it for me instantly.

**Comment by pirate** [comment]
This should be working now with the new full-text link parser. If you try it, let me know if it doesn't work and I'll reopen this ticket.
