### ISSUE TITLE
Set Up Continuous Integration

### ISSUE THREAD

**Issue by Julian** [pirate/ArchiveBox#282]
Possibly I'm missing it but is CI enabled via one of the providers?

(I'm not seeing anything running for the PR I just opened in #281.)

If all it is is running the commands from https://github.com/pirate/ArchiveBox/blob/master/.github/CONTRIBUTING.md#running-tests I'm happy to send a PR adding that too.

**Comment by cdvv7788** [comment]
There is some progress for this. There are tests for the CLI tool using `pytest` that are ran under github actions. This can be improved upon, new tests may be added, and the `archivebox manage test` should be reviewed, but we are getting there.

**Comment by pirate** [comment]
CI is now set up to lint, run tests, and run the docker build + a few test commands. (see the `django` branch, soon to be merged into master)
