### ISSUE TITLE
Is is possible to trigger Webhook after Link has been added?

### ISSUE THREAD

**Issue by fabianmu** [pirate/ArchiveBox#289]
I am wondering if it's somehow possible to trigger a webhook after a link has been crawled and saved?

I do have the following workflow:
1. Add URL into a service/app
2. Have that CMS trigger a scheduled job which runs `echo '$url' | ./archive`
3. Ideally, ArchiveBox would report the URL of the saved entry to my initial service (_ domain/archive/1571939708_)

I could not find any info in the docs or existing issues. An alternative approach that I could look into is weather `./archive` produces return-values that could be interpreted in the scheduled job mentioned in step 2 above.

Any thoughts on how to best achieve this are very much appreciated, Thanks!

**Comment by pirate** [comment]
Scheduled jobs are built into archivebox `>=v0.4`, check out the docs here: https://github.com/pirate/ArchiveBox/wiki/Roadmap#-archivebox-schedule

If you want to manually trigger an import you always have your CMS trigger an `archivebox add '...'` command, and parse the outputted path.

However, that might not be necessary FYI, as if you use `archivebox server` you can just visit `https://127.0.0.1:8000/archive/example.com/path/that/was/archived.html` and it will automatically show you the latest version (meaning you don't have to know the timestamp/id that was assigned during the import process, you can just visit the url directly).

`v0.4` is still not finished, but you can track progress and be notified when it's released by subscribing to the open PRs. https://github.com/pirate/ArchiveBox/pull/207

**Comment by fabianmu** [comment]
Oh ace, the option to just specify an URL to trigger archiving indeed works for my case. Thanks!
