### ISSUE TITLE
Bugfix: hangs when importing .csv, hogs memory

### ISSUE THREAD

**Issue by andrizmitnick** [pirate/ArchiveBox#296]
#### Describe the bug

Importing .csv causes hang, hogging memory. My ram 8gb, swap 16gb.
The file is around 30MB and 190k list.when i try to look into task manager, it seems that archivebox is trying to archive all those list in batch?

#### Steps to reproduce

1. Ran "docker-compose exec archivebox /bin/archive /data/sources/history.csv
2. Saw this output during archiving 'parsing new links from output/sources/history.csv..." 
3. UI didn't show the thing I was expecting, it stuck with only the 1st output, and it hangs a lot, my ram is used %95+ and swap 30%+

#### Screenshots or log output

![MVIMG_20191120_054615](https://user-images.githubusercontent.com/21377475/69193411-3062d600-0b59-11ea-9e8d-51bb22d3cece.jpg)

#### Software versions

 - OS:       manjaro 18.1.3 xfce
 - ArchiveBox version:    94dba22
 - Python version:           3.7.4
 - Chrome version:           80.0.0.3964

**Comment by andrizmitnick** [comment]
Btw i forgot to capture the task manager with VSZ column. I already restarted my laptop, sorry

**Comment by pirate** [comment]
190k is by far the biggest attempted import list I've seen so far, the most been tested before was 60k and it took a powerful machine to complete.  ArchiveBox is not designed to ingest that many things at once, I suggest splitting up your list into separate files and importing them one by-one, each ~1000 links.

```shell-session
$ cd ~/path-to-archivebox/data/sources
$ cp ~/Desktop/big_import_list.txt ./
$ split big_import_list.txt links_chunk_
$ for chunk in links_chunk_*; do docker-compose exec archivebox /bin/archive /data/sources/$chunk; done
# this will run one import for each chunk, duplicates are automatically skipped so it's safe to re-run if cancelled partway through
```

**Comment by pirate** [comment]
I'm going to close this for now because I don't foresee being able to order this large of a list until at least v0.5 (which is a several versions away still).

Performance improvements will come slowly as a result of natural refactoring over time, not as one big PR or issue. You can follow multicore import support here: https://github.com/pirate/ArchiveBox/issues/91, thats the next major performance improvement planned.
