### ISSUE TITLE
Question: Menue instead of loose shell code

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#297]
I think it would be nice to have a little menue instead of echo or else. May something like this:

./archive

(1) I would grab an rss feed
(2) I would like to mirror an complete site
(3) I would save just one webpage
(4) I would like to save a media file (YT/Vimeo/so on)
(5) Make a cronjob
(6) Edit your settings => wizard like settup comes up

Push your number => script takes the best possible script.

---------

What do you think about this?
It may can help to speed up the work and we dont need to use some code. 

Oh and btw, we need ffmpeg and avconv preinstalled (if possible). YTDL sucks a lot without.

Thanks for your great work!

**Comment by pirate** [comment]
Not going to add this, archivebox >= v0.4 will have a web UI to add links, and the CLI is already very different, see https://github.com/pirate/ArchiveBox/wiki/Roadmap
