### ISSUE TITLE
Question: Chromium Timeout

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#298]
I hoped it will changed it, but the cpu / ram cant stop the timeout errors,
so I wished to increased them. The config (not config.default) are still ignored. 
Used the normal git curl.

May it would be a good idea, to increase the timeout by default to ~5 mins?

EDIT: For now I use the config.py and it works perfectly for me.

**Comment by pirate** [comment]
Config handling is massively improved in v0.4, see `archivebox config` here: https://github.com/pirate/ArchiveBox/pull/207 and on the Wiki Roadmap page.

If you still have issues with timeout errors after using v0.4 and the new config system, feel free to open a new ticket for that with a paste of your terminal output or a screenshot + config you're using.
