### ISSUE TITLE
Skip when file is a font/exe/zip

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#299]
## Type 

 - [x] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

When link is a font, it trys to make a pdf or screenshot, which didnt make sense.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Skipping the script when filetype is a font or others which didnt make sense, like exe or zip

## What hacks or alternative solutions have you tried to solve the problem?

actually nothing.
EDIT: I notice that the problem is not happend with pdf files,
so I may can find the correct line to expand them.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

---

 - [x] I'm willing to contribute dev time / money to fix this issue
 - [x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
You're looking for the [`URL_BLACKLIST`](https://github.com/pirate/ArchiveBox/wiki/Configuration#url_blacklist) config option.

Try setting `URL_BLACKLIST= .+\.(exe|woff|otf|ttf)$`
