### ISSUE TITLE
Bugfix: LiveDocumentNotAvailableException

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#300]
> Failed: LiveDocumentNotAvailableException: https://ze.tt/doesnt-spark-joy-marie-kond-lehrte-uns-auszumisten-und-verkauft-nun-dekoartikel/?utm_campaign=ref&amp;utm_content=zett_zon_parkett_teaser_x&amp;utm_medium=fix&amp;utm_source=zon_zettaudev_int&amp;wt_zmc=fix.int.zettaudev.zon.ref.zett.zon_parkett.tease

also 

>  Failed: LiveDocumentNotAvailableException: https://ze.tt/doesnt-spark-joy-marie-kond-lehrte-uns-auszumisten-und-verkauft-nun-dekoartikel/: live document unavailable: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

comes up then the site should be send to archive.org

I think the last can be solved with openssl? 
https://stackoverflow.com/a/42824048

EDIT: OpenSSL dont seems to be the point for my error.

> openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.5).

**Comment by cdvv7788** [comment]
@dataarchivist can you please try on the `django` branch? I am unable to reproduce the issue.

**Comment by pirate** [comment]
If you see this still happening, comment bak here and I'll re-open the issue.
