### ISSUE TITLE
Bugfix: Failed to download media

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#302]
> Failed: Failed to download media
>             Got youtube-dl response code: 1.
>             WARNING: There are no annotations to write.
>             ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
>             built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
>             configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared

Tested site: https://www.bild.de/bild-plus/video/clip/isis/die-isis-braut-teil-1-60156234.bild.html

Used latest updates/upgrades, YTDL (2019-11-05) and latest AB (94dba22).

**Comment by pirate** [comment]
This is an issue with youtubedl for this site, not archivebox, you can submit an issue on their issue tracker to request help.

AB just uses whatever version of YTDL is installed, so if you update it to a version that fixes this bug then it should work fine with AB.  You can confirm it's not ab related by copying the command that AB generates next to "Run this command to see the full error output", if YTDL fails then it's not a bug in AB.
