### ISSUE TITLE
Question: RSSMix useless?

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#303]
I didnt try if AB can do it by itself, but for now, I use http://rssmix.com/ to merge my rss feeds into one to cronjob a lot of websites at once. Its fully free btw.
If its not already possible to catch them easily via txt file or something else, it would be nice to have.

**Comment by pirate** [comment]
Archivebox never re-downloads urls that have been already archived, so you can already pipe in all your RSS feeds without merging / deduplicating them first, so this isn't needed.

**Comment by dataarchivist** [comment]
Is an option to redownload a site again planned?

**Comment by pirate** [comment]
Yes, see https://github.com/pirate/ArchiveBox/issues/179

**Comment by dataarchivist** [comment]
> Archivebox never re-downloads urls that have been already archived

But its does for rss feeds.
So, if you merge the feeds, you normaly get every x hour an fresh rss with new links.

**Comment by pirate** [comment]
> But its does for rss feeds.

 It downloads the feed itself, but it doesn't re-download the pages within it after the first time.

**Comment by dataarchivist** [comment]
> 
> 
> > But its does for rss feeds.
> 
> It downloads the feed itself, but it doesn't re-download the pages within it after the first time.

A normal feed didnt have the same link a second time. ;)
Anyway, I did this with another cron, it was just interesting to know.
