### ISSUE TITLE
Question: how to use Brave Browser or Firefox instead of Chromium?

### ISSUE THREAD

**Issue by JasonMFry** [pirate/ArchiveBox#304]
I'd like to not use Chrome. I'd be happy using either Brave or Firefox. Is that currently possible by changing the some config value? If so, what do I need to do?

**Comment by arch-btw** [comment]
+1 for this request

**Comment by pirate** [comment]
Not going to support that anytime soon, it's just too much work and I barely have any time for this project as-is.  Use webrecorder/pywb instead if you really need it.
