### ISSUE TITLE
Question: Comparison between this and other archival products

### ISSUE THREAD

**Issue by DonaldTsang** [pirate/ArchiveBox#305]
See:
- https://github.com/webrecorder/webrecorder
- https://github.com/webrecorder/pywb
- https://github.com/webrecorder/warcio

1. Are they compatible with one another?
2. Do they produce the same format, or are they different in nature?

**Comment by crislin2046** [comment]
[22120](https://github.com/dosyago/22120) is able to archive everything you browse by hooking into the browser directly. Then offline, you can use your browser as normal, and your browser still works like you're online -- for the pages you've already browsed.

The archive format in 22120 is simple JSON files, organized by directory that represents their origin. There is 1 JSON file for every resource the origin serves you. 

More information about it is in [the README](https://github.com/dosyago/22120/blob/master/README.md)

See: https://github.com/dosyago/22120 for instructions on how to install from the source, or from npm and for the latest binaries see here:
https://github.com/dosyago/22120/releases/latest

**Comment by DonaldTsang** [comment]
@crislin2046 hold on, I am asking for a comparison, not just what they do since ArchiveBox and others are too similar.

**Comment by crislin2046** [comment]
I don't know that much about ArchiveBox so my contribution to the comparison is to share what I know. Other people can then compare with ArchiveBox based on that, using what they know! 😄

**Comment by pirate** [comment]
https://github.com/pirate/ArchiveBox#comparison-to-other-projects
https://github.com/pirate/ArchiveBox/wiki/Web-Archiving-Community#Web-Archiving-Projects

**Comment by DonaldTsang** [comment]
@pirate thanks foe the explanation, but could you describe how WARC differs from the native ArchiveBox format?

**Comment by pirate** [comment]
There isn't really an "ArchiveBox format", it does produce some JSON index files, but really the main output is the output of the tools that it calls to archive each site, e.g.: 

- png: screenshot of the site
- pdf: pdf version of the site
- html: DOM dump of the site rendered in chrome after 2s of JS execution
- WARC: wget WARC archive (same format as pywb output and other tools)
- wget archive: static html + assets as archived by wget, it's normal html, not any proprietary format
- media: e.g. mp3s, movies, git code repositories, etc are all raw fiels, not in any proprietary format

You can find more info here: https://github.com/pirate/ArchiveBox/wiki/Usage#Disk-Layout
