### ISSUE TITLE
Question: Cloning whole site approaches

### ISSUE THREAD

**Issue by ssx** [pirate/ArchiveBox#307]
Hi,

Firstly, a great, polished tool!

Has anyone got AB running in combination with something else to successfully clone an entire site? Having to collect the links of a site manually is a time-consuming process for a few projects I could do with cloning.

I'm curious as to what other tools people are combining this with to create archives of entire sites.

Thanks!

**Comment by ssx** [comment]
Ignore - it appears to do this already, the process had error'd! :)

**Comment by pirate** [comment]
It actually doesn't clone whole sites, so I'm curious as to how you managed to do that with AB.

It is on the roadmap though: https://github.com/pirate/ArchiveBox/issues/191
