### ISSUE TITLE
Server side pagination

### ISSUE THREAD

**Issue by eSoares** [pirate/ArchiveBox#312]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

Currently no pagination is performed in the server side. Yes, jQuery Datatables is used and can provide pagination, but if you amount of links grows it will terribly slow at the opening the page, not solving the problem at all since the problem is the browser render.
The problem are browsers are not designed to handle HTML tree so big.

In my current setup I have archived above 10k urls, which make ArchiveBox almost impossible to open. The index.html file returned from the server is 57MB.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
The best solution would be supporting pagination from server side, and perform AJAX requests on the web page to load more results. 

Extra note: with the pagination, search on the server also needs to be supported. 

## How badly do you want this new feature?

 - [x] It's an urgent deal-breaker, I can't live without it

Currently is a deal breaker for me to use part of the project, since is impossible to even load the start page.

**Comment by pirate** [comment]
This is fixed in v5.0 with `archivebox server` (it's a full Django server with server-side search in v5 and server-side pagination). Follow this PR for future progress https://github.com/pirate/ArchiveBox/pull/275

**Comment by pirate** [comment]
This is released in the new 0.4 branch.
