### ISSUE TITLE
Request for assistance using ArchiveBox #3

### ISSUE THREAD

**Issue by jonconnor67** [pirate/ArchiveBox#326]
Please...I don't have much more time..

**Comment by follower46** [comment]
did you read and try the quickstart guide?
https://github.com/pirate/ArchiveBox#quickstart

**Comment by jonconnor67** [comment]
> did you read and try the quickstart guide?
> https://github.com/pirate/ArchiveBox#quickstart

I can't seem to figure it out!  Please help me!!

**Comment by jonconnor67** [comment]
> did you read and try the quickstart guide?
> https://github.com/pirate/ArchiveBox#quickstart

archive.org deleted every single one of my posts...I ssave the archived version on archive.is, and it's clear as night and day.  The admins lie and say it's an "indexing" issue.  Read that article in the link below and you will understand why I do not believe them

https://archive.is/L3qDC

**Comment by pirate** [comment]
https://github.com/pirate/ArchiveBox/pull/324#issuecomment-597600082
