### ISSUE TITLE
Bugfix: Title with an HTML tags breaks the UI and archive process

### ISSUE THREAD

**Issue by neetij** [pirate/ArchiveBox#330]
#### Describe the bug
Attempting to archive a URL such as [https://24ways.org/2019/it-all-starts-with-a-humble-textarea/](https://24ways.org/2019/it-all-starts-with-a-humble-textarea/), that has an HTML tag in the title, results in failure.  UI breaks, and PDF was not generated.  
Actual title: `It All Starts with a Humble <textarea>`.

![Screenshot_2020-03-18_22-31-41](https://user-images.githubusercontent.com/455781/76959013-a5f47c80-6968-11ea-8060-f46299e87842.png)

#### Software versions
- OS: Ubuntu 18.04.4 LTS (Xubuntu running under VirtualBox 6.1.4 on Windows 10 Home)
- ArchiveBox version: [83197ef]
- Python version: 3.6.9
- Chrome version: 80.0.3987.87

**Comment by pirate** [comment]
related:

- https://github.com/pirate/ArchiveBox/issues/237
- https://github.com/pirate/ArchiveBox/issues/239

**Comment by cdvv7788** [comment]
@neetij this should be solved in the `django` branch, in case you want to give it a try.
