### ISSUE TITLE
Question: Disable Youtube-DL from downloading playlists

### ISSUE THREAD

**Issue by degan6** [pirate/ArchiveBox#332]
Love the project.

I've been running the script for the past few days and noticed that Youtbe-dl is set to download the whole playlist in the link. Is there a supported way to disable this? I have many links in the same playlist.
It seems like it downloaded the entire playlist for each link so I end up with the same video many times.

I've commented line [493 here](https://github.com/pirate/ArchiveBox/blob/4f599c0b0b07c842b1a2d0ec31f229d8fa0d6294/archivebox/archive_methods.py#L493) but I'm hoping for a supported method?

Thank you!

**Comment by cdvv7788** [comment]
https://github.com/pirate/ArchiveBox/issues/503 Will allow you to do this, probably.

**Comment by cdvv7788** [comment]
@degan6 https://github.com/pirate/ArchiveBox/pull/506/files this was merged already. You can play with the config for YOUTUBE_DL and control it however you want. Please reopen if this is not enough for your needs.
