### ISSUE TITLE
Question: Windows 7 and/or Android

### ISSUE THREAD

**Issue by terrypa** [pirate/ArchiveBox#334]
Ok so I like this project BUT I use mainly windows7, dock and WSL don't work so are there any option to run it? or maybe android could run it? if so I could set up smth like this:
- config android firefox to sync history and use archivebox from android phone/second device so it can run in the background without manual VR linux every now and then?
If android could run it what should i read/find? did someone already tried it?

**Comment by pirate** [comment]
You can't use docker for windows? https://docs.docker.com/docker-for-windows/

Unfortunately, I'm not planning on supporting Windows natively anytime soon.

**Comment by terrypa** [comment]
I wish but it works ONLY on windows 10, nothing else and as u know it, windows 10 is one big spy OS
https://docs.docker.com/docker-for-windows/install/

What to know before you install
System Requirements

    Windows 10 64-bit: Pro, Enterprise, or Education (Build 15063 or later).
    Hyper-V and Containers Windows features must be enabled.

    The following hardware prerequisites are required to successfully run Client Hyper-V on Windows 10:
        64 bit processor with Second Level Address Translation (SLAT)
        4GB system RAM
        BIOS-level hardware virtualization support must be enabled in the BIOS settings. For more information, see Virtualization.

**Comment by pirate** [comment]
Meh, if you want to implement it, go ahead, but given my limited time available to work on this project I'm not going to invest it into Android/Windows support.
