### ISSUE TITLE
Feature Request: WEB API

### ISSUE THREAD

**Issue by ddavidebor** [pirate/ArchiveBox#339]
## What is the problem that your feature request solves

I would like to integrate ArchiveBox with open source ERP ERPNext, so that every time an external link is added, ArchiveBox is triggered to scrape it.

## What hacks or alternative solutions have you tried to solve the problem?
Could hack around the CLI, but reliability of such approach is very doubtful and integration is messy

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [X] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

**Comment by pirate** [comment]
This is already planned and in progress, see:

- https://github.com/pirate/ArchiveBox/issues/221
- https://github.com/pirate/ArchiveBox/wiki/Roadmap#-archivebox-server
- https://github.com/pirate/ArchiveBox/blob/django/archivebox/core/urls.py#L22
- https://github.com/pirate/ArchiveBox/blob/django/archivebox/core/views.py#L44
