### ISSUE TITLE
Question: How to archive Facebook pages?

### ISSUE THREAD

**Issue by nihelmasell** [pirate/ArchiveBox#340]
Hi I'm trying to archive a facebook group (its actually a user rather than a group) which post some interesting stuff regarding language learning. I used snscrape to get the list of URLs (nearly 5000). But when I tried to download all those URLS via archivebox I can only grab a hundred, before getting captcha resolves on all the captured pages. Any way to solve this? Any used faced a similar problem? (I could use Tor but it is normally banned ab initio on Facebook). Thanks

**Comment by pirate** [comment]
Rate limiting is a fundamentally difficult part of web archiving, and I'm afraid Archivebox is not designed to handle it interntally.

The expectation is that for users who are archiving 1000s of pages on a single domain, that they set up their own ratelimiting or distributed archiving infrastructure with a proxy bot network of some kind.

While we might add a `RATELIMITS` option in the future to self-regulate how many requests we make to a given domain per minute,hour,day, it's not on the horizon anytime soon (expect >1-2 years), so I'm going to close this issue for now.  Related issues:

- https://github.com/pirate/ArchiveBox/issues/91#issuecomment-489799497
- https://github.com/pirate/ArchiveBox/issues/249
