### ISSUE TITLE
Best Practices for Backup/Restore

### ISSUE THREAD

**Issue by ir0nh3at** [pirate/ArchiveBox#341]
Hello,
I've reviewed the docs, but I don't see any instructions on backup and restore of the downloaded data and database.  Do we just backup the ArchiveBox directory and restore it, or is there more to it than that?  Thanks!

**Comment by pirate** [comment]
Yup, you can zip up the entire folder as a backup, or ideally put it on a filesystem that has COW snapshot support like ZFS, APFS, BTFS, etc.

**Comment by ir0nh3at** [comment]
Perfect.  Just wanted to make sure I wasn't missing something non-obvious.  Thanks for your help.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pirate** [comment]
For anyone who finds this ticket in the future, here's a little more info on the folder structure in the docs (but nothing specific to backups):

- https://github.com/pirate/ArchiveBox/wiki/Usage#Disk-Layout
- https://github.com/pirate/ArchiveBox/wiki/Security-Overview#output-folder
