### ISSUE TITLE
Question: ...How to merge multiple Archive collections

### ISSUE THREAD

**Issue by ekiel** [pirate/ArchiveBox#342]
Right now I’m using ArchiveBox for multiple collections on different machines and the contents are not the same- is it possible to merge the ArchiveBox outputs without having to re-scrape everything?

**Comment by pirate** [comment]
Yup, this is supported natively with the new `archivebox init` feature in `>=v0.4`.  You can drag all the timestamp folders from archive folder to the other, run `init`, and it will import them all, effectively merging the two archives.

The new version also doesn't require keeping the output folder in the same folder as the code, instead you install `archivebox` command system wide or in a virtualenv, and then you can run `archivebox init` in any folder to use it as a data folder.

You can install from the `django` version to try out the early pre-release version, or subscribe to this PR to get notified of when it actually gets merged https://github.com/pirate/ArchiveBox/pull/207 (it may take a while, I rarely have coding time to dedicate to this project theses days).
