### ISSUE TITLE
Question: How can I download just one webpage and not the webpages that are linked to the first one (disable recursion)?

### ISSUE THREAD

**Issue by YousufSSyed** [pirate/ArchiveBox#348]
Let's say I want to download just google.com. I want all of the assets to show that site loaded, but I don't want to archive the webpages that google.com links to, like gmail.com or google.com/images?

**Comment by pirate** [comment]
Archive just one page:
```bash
echo 'https://example.com/some/url/here' | ./archive
```

Archive all the links from an import source (e.g. an RSS feed, page, text file, etc.):
```bash
./archive some/file/example.txt
# or
./archive https://example.com/some/rss/feed.xml
# or
./archive https://example.com/some/page/full/of/urls.html
# etc...
```

This design is changed in [>v0.4](https://github.com/pirate/ArchiveBox/wiki/Roadmap#-archivebox-add) where it becomes:
```
archivebox add 'https://example.com/just/one/page.html'
# or 
archivebox add --depth=1 'https://example.com/one/page/and/all/its/outlinks.html'
# etc.
archivebox add --depth=2 'https://example.com/page/plus/2/hops/of/links.html'
```
