### ISSUE TITLE
Bugfix: django branch dockerfile "cannot create directory..." error

### ISSUE THREAD

**Issue by walkero-gr** [pirate/ArchiveBox#353]
#### Describe the bug
When starting the archivebox container, based on the dockerfile of django branch, I get the following error in logs and it exits

```logs
archive_archivebox   | mkdir: cannot create directory ���/home/archivebox���: Permission denied
archive_archivebox   | touch: cannot touch '/home/archivebox/.local/share/applications/mimeapps.list': No such file or directory
archive_archivebox   | [X] No archivebox index found in the current directory.
archive_archivebox   |     /data
archive_archivebox   |
archive_archivebox   |     Hint: Are you running archivebox in the right folder?
archive_archivebox   |         cd path/to/your/archive/folder
archive_archivebox   |         archivebox [command]
archive_archivebox   |
archive_archivebox   |     Hint: To create a new archive collection or import existing data in this folder, run:
archive_archivebox   |         archivebox init
archive_archivebox exited with code 2
```

I think the above error comes from the following line in dockerfile and because the user `archivebox` doesn't have the right permissions
```
RUN archivebox version
```

#### Steps to reproduce
1. Build archive box image and run the container

#### Software versions

 - OS:                                  macOS 10.14
 - ArchiveBox version:        1866da3

**Comment by walkero-gr** [comment]
I fixed the above issue by adding `--create-home` at the `useradd` command, but I would like your opinion on that.

```
RUN groupadd --system archivebox \
    && useradd --create-home --system --gid archivebox --groups audio,video archivebox
```

**Comment by apkallum** [comment]
@walkero-gr Thanks for the report! This PR should've fixed it: https://github.com/pirate/ArchiveBox/pull/361
