### ISSUE TITLE
Question: Get all links from the same domain

### ISSUE THREAD

**Issue by walkero-gr** [pirate/ArchiveBox#354]
Hello there,
I would like to ask if there is a way to archive a website, and all it's subpages, but without following links to other domains. This is helpful if you need to archive a whole website and preserve it, without be necessary to grab all it's pages by hand and without the risk to get every website when an external domain exist inside the html.

thank you for your time.

**Comment by pirate** [comment]
Duplicate: https://github.com/pirate/ArchiveBox/issues/191
