### ISSUE TITLE
Bugfix: archivebox django branch look

### ISSUE THREAD

**Issue by walkero-gr** [pirate/ArchiveBox#355]
#### Describe the bug
I know that the django branch is a WIP but I would like to be sure there is not a problem on my side, about the look of it. Should it look better than what you see on the screenshot below? If yes, then I can try to find why on my side looks like that. If not, I might be able to help on making it look better with some contribution on my side, if you like.

#### Screenshots or log output

![Screenshot_2020-07-07 Archived Sites](https://user-images.githubusercontent.com/14014909/86784620-a28d1a00-c059-11ea-8305-7efb55a3cf71.png)

#### Software versions

 - OS:                                  macOS 10.14
 - ArchiveBox version:        1866da3

**Comment by pirate** [comment]
Try with `archivebox server` instead of opening the index file directly.

**Comment by cdvv7788** [comment]
I think this PR should have fixed it: https://github.com/pirate/ArchiveBox/pull/360
Can you please confirm @walkero-gr ?
