### ISSUE TITLE
Bugfix: Large index.html crashes browser

### ISSUE THREAD

**Issue by nguyenhaiac** [pirate/ArchiveBox#369]
#### Describe the bug
My index.html after indexing Firefox history created a ~20MB index.html, and it seems like Firefox crash when opening such a large file. This might not be a bug but I just wanna make sure if this is the normal behavior.

#### Steps to reproduce
Indexing Firefox browsing history just as in tutorial

**Comment by cdvv7788** [comment]
Large DOM tend to crash browsers. In the `django` branch we have a django application with pagination to handle this issue. This will be generally available on version 0.4.x. You can check that branch if you want to give it a try right now (remember to backup your archive before doing so).
