### ISSUE TITLE
Bugfix: OUTPUT_PERMISSIONS environment variable appears to not be fully working.

### ISSUE THREAD

**Issue by 1n5aN1aC** [pirate/ArchiveBox#377]
## Describe the bug

I am Testing v0.4.3, to resolve https://github.com/pirate/ArchiveBox/issues/376 and noticed that defining OUTPUT_PERMISSIONS does not seem to be applying to all output files.
I do not know if this is a regression in v0.4.3, or if it exists before, or if I am doing something wrong.

#### Steps to reproduce
I built the container using the following commands:
```
git checkout django
git pull
docker build . -t archivebox:0.4.3
docker run -v "/mnt/data/Archive/ArchiveBox":/data --shm-size 512M --env SUBMIT_ARCHIVE_DOT_ORG=False --env WGET_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/73.0.3683.75 Safari/537.36" --env OUTPUT_PERMISSIONS=755 archivebox:0.4.3 init
docker run -v "/mnt/data/Archive/ArchiveBox":/data --shm-size 512M --env SUBMIT_ARCHIVE_DOT_ORG=False --env WGET_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/73.0.3683.75 Safari/537.36" --env OUTPUT_PERMISSIONS=755 archivebox:0.4.3 add "https://example.com"
```

#### Screenshots or log output

However, the main files that are generated do not have 755 permissions set.  
The files inside the sub-dir example.com **do** appear to have the permission set.
![](https://i.imgur.com/8MeQC31.png)

**Comment by 1n5aN1aC** [comment]
This does appear to also still be the case in the django branch as well.

Interestingly, I noticed that upon running `init` on a new directory, it appears to create the files with the proper (or at least more) permissions before later changing them to the more restrictive 0600 permissions it leaves them with.

**Comment by cdvv7788** [comment]
@1n5aN1aC please test in the django branch again.

**Comment by 1n5aN1aC** [comment]
Progress!

It appears all of the files are now applied the chosen permissions except for output.pdf and screenshot.jpg

![](https://i.imgur.com/Nu7Ek8H.png)

**Comment by pirate** [comment]
Ok I think that's fixed as well in #391 now. If you give it a go now they should all have the same permissions.

**Comment by 1n5aN1aC** [comment]
It does indeed appear to be fixed, thank you very much!  
It looks like it even corrected the permissions on the core index files.

As a bit of an aside, would you be willing to add the "django" branch to docker hub's build system, to make continued testing easier?   No big deal if not, I can keep doing it myself if you'd rather not add it.

**Comment by cdvv7788** [comment]
There are some tests related to docker in github action, and the django branch will be merged to master soon too.
