### ISSUE TITLE
Question: Unable to createsuperuser on Unraid

### ISSUE THREAD

**Issue by smikwily** [pirate/ArchiveBox#395]
Version: .0.4.9 (new install)
OS: Unraid 6.8.3

It is my understanding that Unraid runs as root no matter what (I'm not that technical, but that is my understanding from my research). I finally got archivebox up and running after a morning of tweaking, but I can't create a user for the GUI interface as no matter what I do, I can't run the command "archivebox manage createsuperuser" without it complaining that it shouldn't run as ROOT.

Is there anything I can do to bypass this? I've created a variable ALLOW_ROOT: and set that to True, but it still fails and won't allow me to create a user, so I can't use the GUI to add links, etc, which would be my preferred method of using the software.

Thanks in advance!

**Comment by apkallum** [comment]
Interesting. That's based on FreeBSD right? Did you try running the docker image? Also what's the console output?

**Comment by pirate** [comment]
Docker doesn't exist on FreeBSD 😉 @apkallum 

Also I removed the ALLOW_ROOT intentionally, I don't think it's needed as there is always a way to make a less privileged user and use that instead of root.

Whats preventing you from just running `adduser archivebox; sudo -u archivebox archivebox server` @smikwily?

**Comment by smikwily** [comment]
Honestly, I'm not quite sure how to do that. Let me post on the Unraid forums and see what I can find out. The person making the docker available has admitted that he's just making a template to make it easier to run in Unraid and isn't really set up to handle tech support for it. His instructions have you entering ./archive (URL,FEED,BOOKMARK,FILE) in the post arguments to handle the processing, so it doesn't really use the GUI interface outside of accessing the info. I'd like to be able to sign in and use the GUI to add site that way if possible.

From what I can tell, I do have a user called archivebox created, as when I tried to add it, it said one already existed, but when I try to run it as the user, I'm having issues with it. Let this sit for a little while and I'll see what I can find on my end.

FYI - I found the references to ALLOW_ROOT on the site in the docs, which was throwing me when it was complaining, as it didn't seem to be working as expected. I do feel a bit better knowing you removed it and I wasn't doing something wrong :)

**Comment by apkallum** [comment]
Hmm, I looked a bit at Unraid and it's based on some Linux dist, FreeNAS is what's based on FreeBSD. 
https://wiki.unraid.net/UnRAID_6/Docker_Management 
It looks like they have 'native' docker support in v6

**Comment by smikwily** [comment]
They have a community section that is somewhat like an "app store" approach to allow you to configure things a bit easier. It presents you with some of the variables and paths preconfigured and asks for information for others. 

They have an option as part of that to add things from docker directly via that same interface, but hitting dockerHub as an additional option if it isn't found in the app store. You have to manually enter the variables/paths/ports, etc. using their interface and do some digging to find what you need, which I've gotten a little better at, but I'm nowhere near "full docker user".

I'm a lifetime Windows guy broadening my horizons a bit :)

**Comment by pirate** [comment]
Ah this may be part of what's tripping you up:

> His instructions have you entering ./archive (URL,FEED,BOOKMARK,FILE) in the post arguments to handle the processing

This is the old system and the new docker image is using the new CLI and config system that is very different, likely breaking any setup dependent on the older CLU.

You should be able to run the new docker image without needing to muck around with creating your own user at all on the host. It's compatible with both root and non-root users on the host and handles all of the permissions stuff automatically.

```bash
docker run -v $PWD:/data archivebox init
docker run -v $PWD:/data archivebox manage createsuperuser
docker run -v $PWD:/data -p 8000 archivebox
open https://127.0.0.1:8000
```

**Comment by smikwily** [comment]
That's the thing - I'm not using his method to use the program. I'm trying to use the regular GUI interface vs the CLI interface he's using to get it to work.

I'm still messing around with it, but as it stands, I'm wondering if I won't be able to run it from the "native Unraid interface".

**Comment by cdvv7788** [comment]
@smikwily were you able to solve the issue? Running the instructions @pirate provided should give you a way to start the web interface.

**Comment by pirate** [comment]
Closing this for now, but feel free to comment back here if you still need help.

**Comment by emiliobool** [comment]
Leaving some info here for the people coming from google. To clear the confusion, unraid uses docker for most apps on their "app store", so any docker instructions should work.

You first need to open a shell to the actual unraid server, either via ssh or the GUI. Once there you just need to run:

`docker exec -it --user archivebox archivebox bash`

and after that, once in the container shell you need to follow with:

`archivebox manage createsuperuser`

follow the instructions and that's it.
