### ISSUE TITLE
Question: any import of links within files are failing

### ISSUE THREAD

**Issue by rakunt** [pirate/ArchiveBox#398]
I don't know, do I anything wrong, did I missed some part in the documentation?

The input file can't be more simple... 

```zsh
~/00_Data/ArchiveBox >>> cat google.lst
http://www.google.com
~/00_Data/ArchiveBox >>> archivebox add google.lst
[i] [2020-07-29 23:19:58] ArchiveBox v0.4.9: archivebox add google.lst
    > /home/me/00_Data/ArchiveBox

[+] [2020-07-29 21:19:59] Adding 1 links to index (crawl depth=0)...
    > Saved verbatim input to sources/1596057599-import.txt
Error while loading link! [1596057599.645272] google.lst "None"
    > Parsed 0 URLs from input (Failed to parse)
    > Found 0 new URLs not already in index
```
and generated verbatim input:
```zsh
~/.../ArchiveBox/sources >>> cat 1596057599-import.txt
google.lst% 
```

**Comment by pirate** [comment]
The argument passed gets archived as `--depth=0` by default unless you specify `--depth=1`.

What you want is depth=0 archiving of all the links *within* the file, not the file itself.
```bash
archivebox add < google.lst
```

This also works, but is not really the "correct" way to do it:
```bash
archivebox add --depth=1 google.lst
```

**Comment by rakunt** [comment]
Thanks a lot, not just for your clarification and support, but also for your tool in general.
It's an awesome little helper 👍
