### ISSUE TITLE
Archive Method: add support for SingleFile

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#399]
SingleFile has a CLI that supports using Chrome or FireFox!

This is great news, this is one of the best archiving tools around.

https://github.com/gildas-lormeau/SingleFile/tree/master/cli

**Comment by pirate** [comment]
```python
def save_singlefile(link: Link, out_dir: str):
    CMD = [
        'single-file',
        '--browser-executable-path', CHROME_BIN,
        ...
    ]
    ...
```

With the associated config options, `SAVE_SINGLEFILE`, `SINGLEFILE_BIN`, etc.

**Comment by stevenroose** [comment]
I'm currently trying to use v0.4.11 on Arch and it errors when adding links saying it's missing the SingleFile dependency. But there is no way to install it on Arch. At least not in binary-form.

**Comment by cdvv7788** [comment]
@stevenroose You can use the workaround here https://github.com/pirate/ArchiveBox/issues/427 (or just install it directly using node, as that is the only available way).
