### ISSUE TITLE
Feature Request: Mirror from admin webui

### ISSUE THREAD

**Issue by Facinorous-420** [pirate/ArchiveBox#401]
## Type 

 - [x ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Easy being able to mirror a full website into your archive and have all links you click in your archived version all point to your archiveboxes domain instead of taking you to the original domain

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
I think if we add a mirror option to the add snapshot pages in the admin menu it will solve this. Right now you can only toggle depth, but not enable the mirror flag.
Basically if you check this box when adding from the webui it will use the mirror flag and when it snapshots the webpage it takes all local links in that webpage and replace them with your archiveboxes domain & then continue to snapshot those pages and do it until there are no more pages left. That way you can browse an entire archived website like you can in Wayback

## How badly do you want this new feature?

 - [x ] It's an urgent deal-breaker, I can't live without it / It can wait for the close near future since mirror is already a cli feature (although personally I will be waiting for this to archive into my archivebox as I dread going to cli on the go to add a website)

---

 - [x ] I'm willing to contribute money to fix this issue
 - [ x] I like ArchiveBox so far / would recommend it to a friend

**Comment by pirate** [comment]
Duplicate: https://github.com/pirate/ArchiveBox/issues/191
