### ISSUE TITLE
Question: Archives and PDFs download

### ISSUE THREAD

**Issue by walkero-gr** [pirate/ArchiveBox#404]
When a page has links leading to archives or PDF files, should these be downloaded as well by default, or there is a need for a specific configuration? If not, is it possible to set those files extensions when FETCH_WGET_REQUISITES is true? For example, if I want to set a specific list of files that I would like to download, or set a specific file extensions to be excluded. Whatever is more convenient.

wget has the following parameter for this, which might be helpful
-R,  --reject=LIST               comma-separated list of rejected extensions

**Comment by pirate** [comment]
It will not download *linked* PDFs, video, or downloads unless you pass `--depth=1`, it will however download *embedded* media files, pdfs, etc.s with `--depth=0`, i.e. if they are needed to render the page normally.

- `depth=0` = only archive the url provided and assets needed to render it
- `depth=1` = archive the url provided, then look for all links on the page, and archive those as well, including all assets needed to render those pages (1 hop outwards from the start)
- `depth=2-...` not implemented yet, you probably want to use something like SiteSucker, wget, pywb, etc. to cral for links, then pipe those into ArchiveBox with --depth=0. recursive crawling is difficult and those tools do it better, just use archivebox as the storage and archiving layer instead.
