### ISSUE TITLE
Exception ignored in: io.TextIOWrapper(stdout) BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#406]
#### Describe the bug

*This bug is completely harmless and is visual-only, it can be avoided by setting `SHOW_PROGRESS=False`.*

A macOS-specific bug where the subprocess handler gets killed before the stdout is finished flushing. It catches the exception, but prints it to stderr instead of bubbling up back to user code, so it's impossible to catch and silence from python without monkey patching python internals or doing something crazy.

I've already lost dozens of hours trying to get rid of this, at the moment the only fix is adding a 1sec delay after the process kill, slowing down archiving a lot, or by setting `SHOW_PROGRESS=False` and skipping the subprocess entirely.

#### Screenshots or log output

![image](https://user-images.githubusercontent.com/511499/88972435-89a40d00-d283-11ea-96a5-5a7ae26d7b11.png)

#### Software versions

 - OS:                        macOS 10.15
 - ArchiveBox version:        v0.4.9
 - Python version:            v3.8.5
 - Chrome version:            v84.x.x

**Comment by ryanpcmcquen** [comment]
I've been hit by this as well. What is the effect of this bug?

**Comment by cdvv7788** [comment]
It is just something visual, should not affect the behavior of `archivebox` in any other way.

**Comment by pirate** [comment]
Fixed 🎉 7d4738a
