### ISSUE TITLE
Question: ARM docker images

### ISSUE THREAD

**Issue by walkero-gr** [pirate/ArchiveBox#407]
It would be great if you could provide docker images for ARM processors. Archivebox would be great to be able to work on a RaspberryPi, archiving websites.

**Comment by imlonghao** [comment]
I think use Github Actions to build multi-arch images would be a good solution.

FYI: https://github.com/crazy-max/ghaction-docker-buildx
Usage Example: https://github.com/DIYgod/RSSHub/blob/master/.github/workflows/docker-release.yml

**Comment by pirate** [comment]
Checkout the `docker-arm` branch for arm support!

```bash
git remote update
git checkout docker-arm
docker build . -t archivebox

docker run -v $PWD:/data -p 8000:8000 archivebox server 0.0.0.0:8000
```

Unfortunately the image is 1.25GB because building some python packages on arm requires a C++ compiler, but maybe that can be reduced with multi-stage builds if we figure out where all the built binaries are stored in the OS filesystem.
