### ISSUE TITLE
Bookmarklet support

### ISSUE THREAD

**Issue by jkonrath** [pirate/ArchiveBox#408]
I'm not sure if this fits your general architecture/use-case or how you do this, but would it be possible to make a bookmarklet that when clicked would add the current page in the browser to the archive?

I think Pocket does this, and I remember using it a lot in the del.icio.us days. I'm not sure how exactly you'd do this - maybe add a .js in the server and when it's running, have the bookmarklet call it and submit the URL?

## Type 

 - [ ] General question or discussion
 - [x ] Propose a brand new feature
 - [ ] Request modification of existing behavior or design

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [ x] It would be nice to have eventually

---

 - [ ] I'm willing to contribute dev time / money to fix this issue
 - [ x] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
This is how I run ArchiveBox on my own archivebox right now:

1. Set your Pocket RSS feed to "public" under getpocket.com/privacy_controls
<img width="438" alt="Screen Shot 2020-07-30 at 7 17 40 PM" src="https://user-images.githubusercontent.com/511499/88983587-6d12cf80-d299-11ea-8580-185bc207a407.png">

2. Setup archivebox to import it on a schedule
```bash
archivebox schedule --add --every day 'https://getpocket.com/users/USERNAME/feed/all'
archivebox schedule --show
```

You can also just use normal browser bookmarks and use the browser history import feature:

https://github.com/pirate/ArchiveBox/blob/master/bin/archivebox-export-browser-history

**Comment by jkonrath** [comment]
I don't use Pocket anymore, and want to avoid add a daily reading log to my mostly-static bookmark file. But the second part of your answer made me thought of another way to do this: I could add articles to my reading list in Safari, and then scrape that daily. (Something like https://gist.github.com/andphe/3232343 would work.) Added bonus: anything I add to my reading list on an iCloud-synced iOS device would also end up getting archived.
