### ISSUE TITLE
Documentation: Missing documentation in a few areas

### ISSUE THREAD

**Issue by Jwink3101** [pirate/ArchiveBox#413]
This is pretty general and I may go ahead and add it but I wanted to document it here first.

I am installing archivebox on Webfaction though some of this may be general. And it all may not be documentation

* Some of what is in the reddit reply is not documented. For example, what is `PUBLIC_INDEX`?

* Not (easily) documented how to set the serve port. This is not exactly archivebox per se but it would be good to help with some common options. (answer was to set it in the call)

* No direct way to find commands. For example, calling

        $ archivebox --help
    
    doesn't show commands! The only way to get the list was to do

        $ archivebox fsdsdfdsfsdffsd
    
    And in doing so, it did a bunch of checks (such as Chromium) when it didn't need to.

    (For those reading this the following is the list of options:

    > choose from 'help', 'version', 'init', 'config', 'add', 'remove', 'update', 'list', 'shell', 'manage', 'server', 'status', 'schedule')

    )

There is a few more things but I will break it into separate issues to help with book keeping

**Comment by pirate** [comment]
Are you sure you're on the latest version? Can you post a screenshot of what you see from `archivebox --help`.

<img width="947" alt="Screen Shot 2020-08-01 at 11 25 55 AM" src="https://user-images.githubusercontent.com/511499/89104857-66e03880-d3ea-11ea-90ab-5ed2e3fa0799.png">

**Comment by pirate** [comment]
I'm aware of the missing docs for other things, I already have a PR in progress to fix it all. (The docs have not yet been updated from the last version.)

**Comment by Jwink3101** [comment]
For what it's worth, Using only the version info given by the actual command (why is there no `--version` flag or the link?), I get

```
(archivebox) web545: jwink3101$ archivebox --help
[X] Unable to find a working version of Chrome/Chromium, is it installed and in your $PATH?

Welcome to ArchiveBox v0.4.9!

To import an existing archive (from a previous version of ArchiveBox):
    1. cd into your data dir OUTPUT_DIR (usually ArchiveBox/output) and run:
    2. archivebox init

To start a new archive:
    1. Create an empty directory, then cd into it and run:
    2. archivebox init

For more information, see the documentation here:
    https://github.com/pirate/ArchiveBox/wiki
```

So, no, it doesn't show that. This was installed via pip on the day of my issue post

**Comment by Jwink3101** [comment]
So, it turns out that if you do `archivebox --help` in your data folder, it works as you expect. If you call it not in you data folder, you do not get the expected results.

**Comment by cdvv7788** [comment]
Maybe we could make that more explicit? There are already instructions to import and existing archive and create a new one...maybe some extra paragraph that tells the user that archivebox requires an archive to work properly?
