### ISSUE TITLE
Feature Request: If you can't find chrom(e/ium), stop trying to use it

### ISSUE THREAD

**Issue by Jwink3101** [pirate/ArchiveBox#414]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [X] Request modification of existing behavior or design

## What is the problem that your feature request solves

At every invocation, including `help`, archivebox tells me it can't find chrom(e/ium). This is expected as I do not have it installed (currently using Webfaction. May migrate soon).

But when I go to add a page, it throws errors (in stdout, not on the site) and doesn't archive. To fix this, I set

```bash
export FETCH_SCREENSHOT=False
export FETCH_DOM=False
export FETCH_PDF=False
```

in my invocation script

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Since you already know chromium isn't installed, set those automagically

## What hacks or alternative solutions have you tried to solve the problem?

See above

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [X] It would be nice to have eventually

---

 - [X] I'm willing to contribute dev time / money to fix this issue
 - [X] I like ArchiveBox so far / would recommend it to a friend
 - [X] I've had a lot of difficulty getting ArchiveBox set up
    - See #413 and another I'll be adding in a minute

**Comment by pirate** [comment]
```bash
archivebox config --set USE_CHROME=False
```
<img width="697" alt="Screen Shot 2020-08-01 at 11 29 29 AM" src="https://user-images.githubusercontent.com/511499/89104845-5203a500-d3ea-11ea-85f5-7c1529ba1ab2.png">

**Comment by Jwink3101** [comment]
It is obviously your prerogative on how to handle this but even `USE_CHROME=False` doesn't change the fact that you **know** you don't have chrome.  So it reduces three settings to one but it is still superfluous and causes unexpected errors.

(I *strongly* argue that if the code knows it doesn't have chrome, it shouldn't try and error out)

**Comment by cdvv7788** [comment]
I think erroring out is a sane default. It is explicit behaviour with a known cause. If you want to avoid using chrome, just tell archivebox to avoid trying to use it.
Implicit (automagical) behaviors can obscure issues, and other users will be left wondering why some of their archiving methods are not working as expected. Also, the `USE_CHROME` flag is explicitly telling archivebox to use chrome...changing this to be more `automatic` would require a deeper change to deprecate that flag.

**Comment by pirate** [comment]
I agree with @cdvv7788  Chrome is such a core part of the ArchiveBox feature set that I'd rather make it extremely noisy unless the user explicitly disables it. Implicit disabling of all the chrome methods would leave many users confused as to why it's silently failing on a large number of the archive methods.
