### ISSUE TITLE
Documentation: Improvement request for latest sqlite

### ISSUE THREAD

**Issue by Jwink3101** [pirate/ArchiveBox#416]
## Wiki Page URL

N/A -- though I may add it

## Suggested Edit

This, like some of the issues I brought up in $413 are on the line of what is archivebox's responsibility and what is the user. I think it is a hard line to find but at the same time, you will alienate users who are unwilling or unable to dig too deep. Also, this is arguably a Django problem and/or arguably a Python problem with bad dependancy tracking

This issue may be related to the fact that I do not administer my server. It is hosted on webfaction which gives me non-root shell access and I set up my app to run a specific port.

The main issue is that  Django requires sqlite3 that is newer than some otherwise normal python installs.

My config is roughly:

* create a virtual env pointing to the system python3.7
* `python -m pip install youtube-dl`
* `python -m pip install archivebox`

Then I got all kinds of sqlite errors! I followed the instructions on https://stackoverflow.com/a/57149324 with some modifications to use my own paths. I had to compile sqlite3 (without root) and set the paths (see #415 for this in action)

### Thoughts?

I can add this to the wiki or you can but do you want to? If nothing else, you can close this issue and point people to it should they have a problem

**Comment by pirate** [comment]
I think my recommendation in this case is to just use Docker (or fix the SQLite setup on the host), given this isn't an ArchiveBox-specific bug and the user will likely encounter it with any recent Django/python project trying to use Sqlite3.
