### ISSUE TITLE
Question: archivebox schedule does not work inside docker

### ISSUE THREAD

**Issue by mtvu** [pirate/ArchiveBox#417]
Hi Nick,
Could you give us some instructions on how to set up a scheduled job inside docker. Thanks

![image](https://user-images.githubusercontent.com/4926855/89103031-1c92a200-d452-11ea-9fe4-9166c4a3b54a.png)

**Comment by pirate** [comment]
Just use `--foreground` to run it inside docker. You can see an example in the `docker-compose.yml` file.

**Comment by pirate** [comment]
✅ Fixed in https://github.com/pirate/ArchiveBox/tree/v0.4.15

```bash
docker run -v $PWD:/data archivebox schedule --foreground --every=day --depth=1 'https://getpocket.com/users/USERNAME/feed/all'
```
test it by running jobs immediately in foreground with `--run-all`:
```bash
docker run -v $PWD:/data archivebox schedule --run-all --every=day --depth=1 'https://getpocket.com/users/USERNAME/feed/all'
```
