### ISSUE TITLE
Bugfix: github.com archive css issue

### ISSUE THREAD

**Issue by john-clark** [pirate/ArchiveBox#418]
#### Describe the bug
Github archive issue

#### Steps to reproducem

1. Ran ArchiveBox on github.com page
2. CSS on wget clone doesn't seem to be working
3. Screenshot and pdf look fine

#### Screenshots or log output

![image](https://user-images.githubusercontent.com/3967451/89103802-34c6da80-d3da-11ea-931a-1d9ab17aa9e1.png)

#### Software versions

 - OS:                        Debian 10
 - ArchiveBox version:        7ec1e35
 - Python version:            Python 3.7.3
 - Chrome version:            Chromium 83.0.4103.116 built on Debian 10.4, running on Debian 10.4

**Comment by pirate** [comment]
Yeah this is just the result wget produces, it's a known thing and not a bug with ArchiveBox.

I recommend using the HTML dump, PDF, screenshot, or other methods for Github.
