### ISSUE TITLE
Question: What is the minimum recommended amount of RAM

### ISSUE THREAD

**Issue by berezovskyi** [pirate/ArchiveBox#419]
Hello,

I am thinking to deploy ArchiveBox on a VM or to buy a new RPi 4 for this. What is a minimum amount of RAM needed for the ArchiveBox to function well? The options with RPi are 2, 4, and 8GB RAM and for DigitalOcean VMs or alternatives it's 1, 2, 4, 8GB. The https://github.com/pirate/ArchiveBox/wiki/Install#supported-systems does not mention RAM requirements or whether it will run on Linux/ARM.

Thanks in advance!

**Comment by pirate** [comment]
500MB bare minimum, 2GB recommended. You basically need enough to run Chrome and hold your whole index in memory.
