### ISSUE TITLE
Feature Request: Reverse Proxy the Admin Pages

### ISSUE THREAD

**Issue by jpartain89** [pirate/ArchiveBox#423]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [ X ] Request modification of existing behavior or design

## What is the problem that your feature request solves
Being able to access the admin pages through the regular URL that we setup for the archive.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes
This is sort of in relation to #221, where we'd be able to access the admin pages through an NGINX proxy, making the business end of the ArchiveBox much more easily accessible. Plus, providing a nice how-to plus config example to help us out.

## What hacks or alternative solutions have you tried to solve the problem?
I've tried making a reverse proxy configuration similar to my other reverse proxies. It doesn't quite load anything right. 

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ X ] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [ X ] I'm willing to contribute dev time / money to fix this issue
 - [ X ] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by pirate** [comment]
Hmm it should work out of the box with the admin UI behind a reverse proxy. What errors are you seeing exactly?
Here's an example Caddy 2 config:
```
archive.example.com {
    reverse_proxy 127.0.0.1:<published port>
}
```

**Comment by daviddavo** [comment]
The problem happens when you set the reverse proxy in a subfolder instead of a subdomain

`location /archivebox/` fails because it redirects to `/public`, which does not fall behind the reverse proxy location, so it gets a 404 error
