### ISSUE TITLE
Question: Tags separation

### ISSUE THREAD

**Issue by walkero-gr** [pirate/ArchiveBox#425]
How can I separate multiple tags in an archive. Checked the documentation and didn't find something on that. Maybe I missed it.
A help text on the form would be also useful.

Thanks for your time.

**Comment by pirate** [comment]
Tags are stored as a single comma-separated string for now. They'll be split out into a separate one-to-many foreign-keyed model in a future version.

**Comment by drpfenderson** [comment]
@pirate Is there a way to edit the stored tags on a link in the current version? Or is this more of a future functionality as you mention?

**Comment by cdvv7788** [comment]
@drpfenderson I literally just added that in the PR for the upcoming release. It will be editable in the admin.

**Comment by pirate** [comment]
Closing this because it's finished in the latest release.
