### ISSUE TITLE
Question: SINGLEFILE_BINARY missing

### ISSUE THREAD

**Issue by oksjd** [pirate/ArchiveBox#427]
Installed on Debian 10. The `single-file` command is missing after running `pip3 install archivebox` and I haven't managed to find which package contains this binary. 

Might be a dumb question but I couldn't find the answer with Google given such a generic name.

**Comment by cdvv7788** [comment]
@oksjd we recently added a new extractor named `single-file`. The shortest way is to set `USE_SINGLEFILE=false` in the environment. You can also install it (https://github.com/gildas-lormeau/SingleFile/tree/master/cli) and set `SINGLEFILE_BINARY` to the path of the executable.

**Comment by oksjd** [comment]
Thanks! This workaround fixed the issue.

**Comment by pirate** [comment]
@cdvv7788 can you add a helptext that prints the download link for singlefile when it's missing and not set to use=false
