### ISSUE TITLE
Bugfix: Inconsistent timezones in output

### ISSUE THREAD

**Issue by pigmonkey** [pirate/ArchiveBox#428]
I installed v0.4.11 and added new URLs from my Pinboard export:

```
$ archivebox add < ~/library/conf/pinboard.json
[i] [2020-08-07 10:13:29] ArchiveBox v0.4.11: archivebox add < /dev/stdin
    > /home/pigmonkey/tmp/bookmarks

[+] [2020-08-07 17:15:07] Adding 860 links to index (crawl depth=0)...
    > Saved verbatim input to sources/1596820507-import.txt
    > Parsed 860 URLs from input (Generic JSON)
    > Found 5 new URLs not already in index

...
```
The first timestamp (10:13:29) is in my system's localtime. The second timestamp (17:57:07) is not, in fact, 7 hours later. It is 2 minutes later, but in UTC.

I don't have a strong preference for which of the two timezones ArchiveBox should use in its output, but I do have a strong preference for consistency. Indicating the offset for whichever timezone is used would also be great.

**Comment by apkallum** [comment]
Honestly I tried multiple combinations and still get correct timestamps, even though the code does sometimes handle them a little differently. 

e.g:
```
$ archivebox add < index.json

[+] [2020-08-10 20:46:19] Adding 80 links to index (crawl depth=0)...
    > Saved verbatim input to sources/1597092379-import.txt
    > Parsed 8 URLs from input (Plain Text)
    > Found 4 new URLs not already in index

[*] [2020-08-10 20:46:19] Writing 4 links to main index...
    √ /home/apkallum/projects/ab4/ArchiveBox/output/index.sqlite3
    √ /home/apkallum/projects/ab4/ArchiveBox/output/index.json
    √ /home/apkallum/projects/ab4/ArchiveBox/output/index.html

[▶] [2020-08-10 20:46:19] Collecting content for 4 Snapshots in archive...
```

Maybe it's pinboard specific, would you mind sharing your pinboard.json or part of it?

**Comment by pirate** [comment]
@pigmonkey try on the latest master version I think we've fixed it to be UTC everywhere.

```bash
git checkout master
git pull
pip install .
cd path/to/data/dir
archivebox add https://example.com/#test2
```

**Comment by pirate** [comment]
If you still see any issues comment back and I'll reopen this.

**Comment by pigmonkey** [comment]
Yes, that fixed it. The timestamps are all UTC now in v0.4.14. Thanks!
