### ISSUE TITLE
Bugfix: chromium open multiple tabs is only supported when remote debugging is enabled

### ISSUE THREAD

**Issue by arturi** [pirate/ArchiveBox#429]
Thank you for the awesome work on ArchiveBox!

#### Describe the bug
Getting the below error on `archivebox add` when trying to make pdf/screenshot with chromium. Additionally getting `xdg-settings: not found`.

```sh
Failed:
             Failed to save PDF
            /usr/bin/chromium-browser: 12: xdg-settings: not found
            [0808/101304.953382:ERROR:headless_shell.cc(174)] Open multiple tabs is only supported when remote debugging is enabled.
        Run to see full output:
            cd /mnt/disk/archivebox/archive/1596881575;
            chromium-browser --headless "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36" --window-size=1440,2000 --timeout=60000 --print-to-pdf https://example.com
```

#### Steps to reproduce
Ran ArchiveBox as `archivebox add https://example.com`

#### Software versions

 - OS: Ubuntu 20.04.1 LTS 
 - ArchiveBox version: ArchiveBox v0.4.11
 - Python version: Python 3.8.2
 - Chrome version: Chromium 84.0.4147.105 snap

**Comment by pirate** [comment]
Can you run these commands manually and post the output:

```bash
xdg-mime query default x-scheme-handler/https
cd /mnt/disk/archivebox/archive/1596881575
chromium-browser --headless --timeout=60000 --print-to-pdf 'https://example.com'
chromium-browser --headless --timeout=60000 --print-to-pdf=output.pdf 'https://example.com'  # note the extra arg
```

**Comment by zachscheider** [comment]
I was also getting the 'multiple tabs' error with that same chromium snap version. It impacted screenshots and DOM dumps too.

Updating to edge fixed it for me.
`sudo snap refresh --edge chromium`

https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1887795

**Comment by pirate** [comment]
Since this can be fixed by upgrading chromium, I'm going to close it here. Thanks for reporting this and posting the link to the fix!
