### ISSUE TITLE
links in archives doesn't goto local copy

### ISSUE THREAD

**Issue by NavnDK** [pirate/ArchiveBox#431]
#### Describe the bug

when in a archive and i click on a link it sends me to that url example.com/some-cool-thing.php instead of https://example.net/archive/123/example.com/some-cool-thing.php
#### Steps to reproduce

mkdir archiveBox
docker run -v /srv/archiveBox:/data nikisweeting/archivebox init
docker run -v /srv/archiveBox:/data nikisweeting/archivebox add --depth 1 'https://example.org'
docker run -v /srv/archiveBox:/data -p 8000 nikisweeting/archivebox server 0.0.0.0:8000

then i goto firefox and open the archive
https://example.net/archive/456/example.org/index.html
and click on link

#### Software versions

 - OS:                        ([e.g. macOS 10.14] the operating system you're running ArchiveBox on)pop os 18.04
 - ArchiveBox version:        (`git rev-parse HEAD | head -c7` [e.g. d798117] commit ID of the version you're running)the newest one from docker
 - Python version:            (`python3 --version` [e.g. 3.7.0])3.6.9
 - Chrome version:            (`chromium-browser --version` [e.g. 73.1.2.3] if relevant to bug)i don't use chrome

**Comment by cdvv7788** [comment]
@NavnDK to the right in the admin, there are several icons (one per each extractor used). Are those not working either?

**Comment by NavnDK** [comment]
> @NavnDK to the right in the admin, there are several icons (one per each extractor used). Are those not working either?

i can't even make an account... i have no idea what TTY is in this case

"[i] [2020-08-09 00:43:48] ArchiveBox v0.4.11: archivebox manage createsuperuser < /dev/stdin
    > /data

Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually."

**Comment by cdvv7788** [comment]
try `docker run -v /srv/archiveBox:/data -p 8000 nikisweeting/archivebox manage createsuperuser`

**Comment by NavnDK** [comment]
> try `docker run -v /srv/archiveBox:/data -p 8000 nikisweeting/archivebox manage createsuperuser`

that is what i did

**Comment by pirate** [comment]
In order to run interactive commands in docker you need to pass `-i`, when using docker-compose this is handled automatically and isn't needed.

This is the command you want:
```bash
docker run -v /srv/archiveBox:/data -it nikisweeting/archivebox manage createsuperuser
```

**Comment by pirate** [comment]
Added a helptext hint for the docker thing: https://github.com/pirate/ArchiveBox/commit/33ab7fd4ec1204c9a917fb04674d43ab6aec304e#diff-c4c25449ac3ca50a6c65236fad6f42deR1063-L1063
