### ISSUE TITLE
Bugfix: 4.16 - No readability output when archiving

### ISSUE THREAD

**Issue by winteriscariot** [pirate/ArchiveBox#450]
#### Describe the bug
When I archive a link, there's no readability directory:

/archive/1597758864/readability/content.html < this directory is not created, even though the ArchiveBox web UI shows the link, which then proceeds to 404 because the readability directory doesn't exist.

#### Steps to reproduce
Run ArchiveBox with the following env flags:

OUTPUT_DIR=/home/winteriscariot/.archivebox
CHROME_USER_DATA_DIR=/home/winteriscariot/.config/chromium/Default 
CHROME_BINARY=/usr/bin/chromium 
SUBMIT_ARCHIVE_DOT_ORG=False 
FETCH_MEDIA=False 
OUTPUT_PERMISSIONS=755 
COOKIES_FILE=/home/winteriscariot/cookies.txt

#### Software versions

 - OS:                        Arch Linux
 - ArchiveBox version:        ArchiveBox v0.4.16
 - Python version:            Python 3.8.5
 - Chrome version:            Chromium 84.0.4147.105 Arch Linux

**Comment by winteriscariot** [comment]
It looks like some methods are being skipped and I'm not sure why:

```
[+] [2020-08-18 14:07:46] "www.marketwatch.com/news/story.asp?guid=%7B4F246FDA-E151-11EA-827E-551CAC965F72%7D"
    http://www.marketwatch.com/news/story.asp?guid=%7B4F246FDA-E151-11EA-827E-551CAC965F72%7D
    > ./archive/1597759665
      > title
      > favicon                                                                                                        
      > wget                                                                                                           
      X singlefile                                                                                                     
      > pdf
      > screenshot                                                                                                     
      > dom                                                                                                            
      X readability                                                                                                    
      X git
      > media
      > archive_org                                                                                                    
                                                                                                                       
[√] [2020-08-18 14:08:01] Update of 1 pages complete (15.70 sec)
    - 0 links skipped
    - 1 links updated
    - 0 links had errors

```

Is there an env option I have to set in order to get the Readability output to properly fire? Or is there a prereq that I missed that I need to install?

**Comment by pirate** [comment]
Try the latest version of archivebox v4.17, it adds some helptext explaining how to install SingleFile and Readability:
```bash
pip install --upgrade archivebox
npm install -g 'git+https://github.com/pirate/readability-extractor.git'
npm install -g 'git+https://github.com/gildas-lormeau/SingleFile.git'
```

**Comment by winteriscariot** [comment]
hm yeah it looks like the Docker version is working without any hiccups, I can slot this into my workflow so this should fix my issues.

Thanks for the response! Great project you have here. :)
