### ISSUE TITLE
Feature Request: Public / Anonymous mode

### ISSUE THREAD

**Issue by techied** [pirate/ArchiveBox#455]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [X] Request modification of existing behavior or design

## What is the problem that your feature request solves

I need anonymous users to be able to add links to Archivebox

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

I'd like an option to enable "public" mode, in this mode any user can add links to the Archivebox instance. In this way, it is somewhat of a self-hosted wayback. Links can be added and the link list can be browsed without login of any kind. Deleting links, overwriting, etc. are still reserved for logged in users.

## What hacks or alternative solutions have you tried to solve the problem?

A workaround is to create a user for everyone to use, and post this login publicly, although the problem with a public facing instance is that then anyone can overwrite & remove other links.

## How badly do you want this new feature?

 - [X] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [ ] It would be nice to have eventually

---

 - [X] I'm willing to contribute dev time / money to fix this issue
 - [X] I like ArchiveBox so far / would recommend it to a friend
 - [ ] I've had a lot of difficulty getting ArchiveBox set up

**Comment by apkallum** [comment]
@techied sorry for the delay, but I'm happy to tell you that it's already been implemented. There is a config flag called `PUBLIC_ADD_VIEW`, if you set it to `True`, you should be able to access the add view without logging in.

**Comment by Flightkick** [comment]
Great! It would be nice if this flag was added to the [configuration documentation](https://docs.archivebox.io/en/master/Configuration.html).
I now see that it's mentioned in other sections but I had to dive through search engines and GitHub issues to find it.

**Comment by pirate** [comment]
Alas the wiki has become slower to update ever since someone started adding virus links and I had to remove public edit permissions. I will add this to the queue, thanks!
