### ISSUE TITLE
Question: can anon access be disabled?

### ISSUE THREAD

**Issue by zblesk** [pirate/ArchiveBox#472]
I just found ArchiveBox today and will gladly scrap my homebrew archival solution. Great work! 

I definitely don't want to have my archive exposed to the world, though. I need the user to be logged in befoe accessing anything. Can this be turned on? I haven't found anything like this so far. 

Thanks again!

**Comment by apkallum** [comment]
There are a few relevant options depending on how you want to configure it. For now, there is `PUBLIC_INDEX` & `PUBLIC_SNAPSHOTS`, both of which you can set to `False`. In the next release (0.5) which should be this week, there will be an option to also enable or disable a the add view for non-logged in users.

**Comment by zblesk** [comment]
Thank you! Seems to work!

I can't find any docs for that. WHat happens if I disable Index but enable Snapshots? Will I be able to hotlink articles, but only logged in users will be able to search/see the list? 
Is that a supported use-case?

**Comment by pirate** [comment]
Yes, that is a supported use case, and it should work exactly as you described.

`PUBLIC_SNAPSHOTS` = anon users can view hotlinked archived sites
`PUBLIC_INDEX` = anon users can view the full archive index
