### ISSUE TITLE
Feature Request: Switch from youtube-dl to youtube-dlc

### ISSUE THREAD

**Issue by kimreyio** [pirate/ArchiveBox#474]
- [ X ] Request modification of existing behavior or design

- Feature Request Reason: Change to new fork of youtube-dl for better site compatibility and ongoing development since youtube-dl seems to be unmaintained.

- Ideal Solution: Replace youtube-dl with youtube-dlc in the dockerfile & any other dependency 
Youtube-dlc link https://github.com/blackjack4494/youtube-dlc

- Hacks/Alternatives: symlinking.

 - [ X ] It would be nice to have eventually

 - [ X ] I like ArchiveBox so far / would recommend it to a friend

Love the app!

**Comment by pirate** [comment]
We'll check it out and test if it indeed works for all the common use cases. 

In the meantime, if it's a drop-in replacement and you want to use it ASAP, you can set the config value / environment variable `YOUTUBEDL_BINARY=/some/path/to/youtube-dlc`.

`archivebox config --set YOUTUBEDL_BINARY=/some/path/to/youtube-dlc`

**Comment by cdvv7788** [comment]
I checked youtube-dl's github: https://github.com/ytdl-org/youtube-dl/
It is still active as a project, with a new version released yesterday. I don't think it is worth changing it at this point, given that it is not actually an unmaintained project. Maybe if it starts getting ahead `feature wise` it could make sense.

**Comment by kimreyio** [comment]
This can be closed, seems they'll probably start working through their PR's after a fork (or 3 now) have popped up too. Awesome that the specific binary can be set with a config option in ArchiveBox. Thank again for the app.
