### ISSUE TITLE
Is It Possible To Run The Web GUI In A Docker Container On HTTPS Without Using A Reverse Proxy?

### ISSUE THREAD

**Issue by mcbeav** [pirate/ArchiveBox#476]
For a complicated reason, I need to be able to expose the web ui's port of a docker container instance of archive box as https without using a reverse proxy or nginx. In the installation is specifically says HTTP and NOT HTTPS. Is it possible to change this, and if so, how would I go about doing so?

**Comment by apkallum** [comment]
The archivebox container itself does not (and will not) implement an HTTPS connection to itself. Is there a problem with using something like a [caddy container](https://registry.hub.docker.com/_/caddy) in front of it?
