### ISSUE TITLE
Archiving strategy

### ISSUE THREAD

**Issue by mtvu** [pirate/ArchiveBox#477]
Hi Nick, 

I'm currently running archivebox to download all articles from my Pocket service. The size of the downloaded archives is getting larger and I might run out of space on the current disk where I host archivebox. Just wondering if you have any suggestion for archiving the downloaded files. My plan is to run a script which archives ( using tar ) all files downloaded for the month. Hope you have a better solution to share . 

Thanks 
Tuan

**Comment by apkallum** [comment]
Are you asking how to archive your archived pages once they are done to save space? `tar` works to reduce total space for non-media files, for media files you can set the `youtube-dl` binary to download with a lower quality. If you can get those files on your personal computer that runs macOS or Windows, you can archive unlimited amount of data for $6/month or pay as you go with something like Backblaze: https://www.backblaze.com/cloud-backup.html

**Comment by mtvu** [comment]
Thanks @apkallum for the suggestion. I'll probably look into reducing the quality of downloaded youtube videos as they do take a bit of space. My current strategy is to create incremental tar backup files. These archive files will then be moved to Google Team Drive with rclone.

**Comment by pirate** [comment]
@mtvu the recommended approach is to use a compressed + deduped filesystem like ZFS. That will get you the maximum amount of space savings without having to reduce archive quality or manually tar and untar individual files.

https://constantin.glez.de/2011/07/27/zfs-to-dedupe-or-not-dedupe/
