### ISSUE TITLE
Feature Request: Allow custom DNS -- Blocking Google DNS causes features to fail

### ISSUE THREAD

**Issue by winteriscariot** [pirate/ArchiveBox#497]
## Type 

 - [ ] General question or discussion
 - [ ] Propose a brand new feature
 - [x] Request modification of existing behavior or design

## What is the problem that your feature request solves

When there is no access to Google's DNS (such as if 8.8.8.8 and/or 8.8.4.4 are blackholed) certain failures occur, including retrieval of page title and a number of archival methods, such as Singlefile.

## Describe the ideal specific solution you'd want, and whether it fits into any broader scope of changes

Being able to define which DNS servers to use in ArchiveBox configuration would be ideal, but even if it just listened to whatever is in /etc/resolv.conf or otherwise used by the system, that'd be nice.

## How badly do you want this new feature?

 - [ ] It's an urgent deal-breaker, I can't live without it
 - [ ] It's important to add it in the near-mid term future
 - [x] It would be nice to have eventually

**Comment by pirate** [comment]
That seems odd, it should be using whatever the system default is right now. The only think I can think of is if Chrome hardcodes some 8.8.8.8 DNS hits internally. (Screenshot, PDF, DOM dump, and SingleFile all use Chrome headless)

Does it work with docker compose?

```yaml
archivebox:
   image: nikisweeting/archivebox:latest
   dns:
       - 1.1.1.1
   volumes:
       - ./data:/data
```

**Comment by winteriscariot** [comment]
oooh I hadn't considered that it would be a Chrome issue and not an archivebox issue. I'll look into that further; I'm not using docker so the docker compose bits don't apply to me. I'll close this issue for now as a functional workaround is capturing _all_ DNS requests on my network and forwarding to my pihole (mostly to adblock youtube ads on my chromecast but that's a separate thing).

Thanks!
