### ISSUE TITLE
Question: [X] Unable to find a working version of Chrome/Chromium, is it installed and in your $PATH?

### ISSUE THREAD

**Issue by XDavidT** [pirate/ArchiveBox#501]
I just used installed ArchiveBox on Ubuntu Server 20.04 using pip3.
I can't archive anything since I get this error every time:

> [X] Unable to find a working version of Chrome/Chromium, is it installed and in your $PATH?

Trying to add more site:
`! CHROME_BINARY: unable to find binary (unable to detect version)`

**Comment by cdvv7788** [comment]
@XDavidT you need to install chrome as mentioned in the [quickstart](https://github.com/pirate/ArchiveBox#quickstart). You can also disable it, but then half of the extractors will be disabled along chrome.
You will also need to install node and run npm install.

Docker provides a way to run `archivebox` easily, in case this is proving difficult.

**Comment by XDavidT** [comment]
I think we need to put it before 'How does it work?'
Thx!
