### ISSUE TITLE
Add ability to configure arbitrary additional CLI args for each dependency

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#503]
I'm imagining a feature like this:

`config.py`:
```python
YOUTUBEDL_ARGS = ['-f', 'bestvideo[filesize<500M][height<=?480]+bestaudio/best']
...
WGET_ARGS = ['--no-warc-compression']
...
```

`extractors/youtubedl.py`:
```python
...
CMD = [
    YOUTUBEDL_BIN,
    ...
    *YOUTUBEDL_ARGS,
]
...
```

This will allow people to self-configure the extractor behavior with much more customizability, without requiring archivebox-level config flags for each separate feature.

**Comment by cdvv7788** [comment]
How does this work with the refactor to django's settings? Can it be done at the same time? should we get this one out first?

**Comment by pirate** [comment]
Don't bother with the Django settings refactor for now, I have an idea of how to do it and I'd like to do it myself later on with a module re-organization. Get this one out first as it's quite simple.

**Comment by cdvv7788** [comment]
@pirate we have the following `cmd` in the `media` extractor:
```
cmd = [
        YOUTUBEDL_BINARY,
        '--write-description',
        '--write-info-json',
        '--write-annotations',
        '--write-thumbnail',
        '--no-call-home',
        '--no-check-certificate',
        '--user-agent',
        '--all-subs',
        '--extract-audio',
        '--keep-video',
        '--ignore-errors',
        '--geo-bypass',
        '--audio-format', 'mp3',
        '--audio-quality', '320K',
        '--embed-thumbnail',
        '--add-metadata',
        *(['--yes-playlist'] if SAVE_PLAYLISTS else []),
        *([] if CHECK_SSL_VALIDITY else ['--no-check-certificate']),
        link.url,
    ]
```
The idea is to remove `SAVE_PLAYLISTS` and `CHECK_SSL_VALIDITY` and pass the new `YOUTUBEDL_ARGS` config, right? The default should contain all of these defaults?

**Comment by cdvv7788** [comment]
@pirate I just pushed a commit (https://github.com/pirate/ArchiveBox/pull/506). Can you please check if that is what you had in mind? I will wait until you check it to move forward with other extractors.

**Comment by cdvv7788** [comment]
@pirate Closing this. Please reopen if there is something else we are missing for this.
