### ISSUE TITLE
Setting CHROME_USER_DATA_DIR

### ISSUE THREAD

**Issue by ThomDap** [pirate/ArchiveBox#516]
Hi, I am struggling to set my CHROME_USER_DATA_DIR in order to archive some webpages behind logins-walls.
Cf screenshots.
Thank you for your help.

<img width="455" alt="Screen Shot 2020-10-29 at 16 42 06" src="https://user-images.githubusercontent.com/10841592/97597404-12a71d80-1a06-11eb-895c-2fd5dcfcbcb8.png">
<img width="963" alt="Screen Shot 2020-10-29 at 16 44 39" src="https://user-images.githubusercontent.com/10841592/97597416-16d33b00-1a06-11eb-8dcf-4bb8f6be85ea.png">

**Comment by cdvv7788** [comment]
@ThomDap According to https://github.com/pirate/ArchiveBox/wiki/Configuration#chrome_user_data_dir , I ran that command passing a folder with a `Default` inside, and I got:

```
❯ archivebox config --set CHROME_USER_DATA_DIR="./test"
[i] [2020-10-29 16:02:49] ArchiveBox v0.4.21: archivebox config --set CHROME_USER_DATA_DIR=./test
    > /Volumes/home/ArchiveBox/archive_folder/archive_folder

CHROME_USER_DATA_DIR=/Volumes/home/ArchiveBox/archive_folder/archive_folder/test
```

Double check that your folder has a file named `Default`.

**Comment by cdvv7788** [comment]
I found an issue with this setup and you will likely find it if you set the folder correctly. I created a PR for it, so it should make it to master soon. By the way, what version are you running?

**Comment by ThomDap** [comment]
@cdvv7788 Thank you for your very quick reply.
I triple-checked the instructions of the wiki. There is a Default folder in my Chrome folder, you can see it in the screenshot. 
I'm running the lastest version.

**Comment by cdvv7788** [comment]
Can you try with the current `master`? Take a backup of your archive before that.

**Comment by ThomDap** [comment]
Just tried with the new master. I got this error : 
![image](https://user-images.githubusercontent.com/10841592/97608598-d928df00-1a12-11eb-9754-a61c20b5173f.png)

**Comment by ThomDap** [comment]
👏👏  I typed the entire command by hand (I didn't paste it) ant it worked ! 
Thanks a lot

**Comment by cdvv7788** [comment]
Not sure in your case. We have big changes between v0.4 and v0.5, so it may have been fixed in there. I created a PR for an issue that is still happening in master tho, so we are still ironing it out.
If you find any issue, let us know. Thanks!
