### ISSUE TITLE
Archive Method: Wget: Detect and fix downloaded file encodings to utf-8

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#52]
Best guess for encoding:
```bash
$ file -bi archive/1509683331/blog.wesleyac.com/posts/two-interview-questions.html
application/gzip; charset=binary
```

First un-gzip any gzipped files:
```bash
gunzip < archive/1509683331/blog.wesleyac.com/posts/two-interview-questions.html > archive/1509683331/blog.wesleyac.com/posts/two-interview-questions.decoded.html
```

Then re-detect encoding and normalize to UTF-8
```bash
iconv -f ISO-8859-1 -t UTF-8 archive/1509683331/blog.wesleyac.com/posts/two-interview-questions.html > archive/1509683331/blog.wesleyac.com/posts/two-interview-questions.decoded.html
```

**Comment by Offirmo** [comment]
Real case: I archived http://catb.org/jargon/html/index.html

Original: 
![Screen Shot 2019-03-19 at 16 57 01](https://user-images.githubusercontent.com/603503/54584022-381e2800-4a6a-11e9-990f-9d0da8848033.png)

Archived:
![Screen Shot 2019-03-19 at 16 57 08](https://user-images.githubusercontent.com/603503/54584026-3d7b7280-4a6a-11e9-9828-db1aa2a212fa.png)

too bad...

**Comment by pirate** [comment]
@Offirmo don't worry, the byte-for-byte data from the server is saved correctly in the WARC.  Even though it's displaying incorrectly now, as we add encoding fixes later on it will update and fix older previously mangled/badly-decoded archives to display correctly.

**Comment by cdvv7788** [comment]
@Offirmo I just tried with the django branch: `archivebox add http://catb.org/jargon/html/index.html` and it seems to be working correctly now.
@pirate I guess this has been fixed since. Can you please confirm and close the issue if that is the case?

**Comment by pirate** [comment]
@Offirmo if you see any further encoding issues on the latest `django` version feel free to comment back here and I can reopen this ticket.
