### ISSUE TITLE
any docker image command results in "[dumb-init] No such file or directory"?

### ISSUE THREAD

**Issue by tmladek** [pirate/ArchiveBox#526]
I'm trying to follow the guide in the README, but no matter what command I run with the image, I get basically the same error:

```
$ docker run -v ~/archivebox:/data -it nikisweeting/archivebox manage createsuperuser
[dumb-init] manage: No such file or directory
```
Or with docker-compose:
```
$ docker-compose run init
[dumb-init] init: No such file or directory
```

```
$ docker-compose up
Starting archivebox_archivebox_1 ... done
Attaching to archivebox_archivebox_1
archivebox_1  | [dumb-init] server: No such file or directory
archivebox_archivebox_1 exited with code 2
```

I looked around in the project's issues and also tried Googling, but of no avail.

**Comment by cdvv7788** [comment]
@tmladek what Image are you using? I am testing with the current master and I cannot reproduce it.

**Comment by tmladek** [comment]
Oh wow, that's stupid! I did have an outdated image, I must have already tried to run archivebox on that machine and forgot about it. I thought that by running `nikisweeting/archivebox:latest` as per the `docker-compose.yml`, I am really getting the `latest` image.

Anyway, thanks!
