### ISSUE TITLE
Changine Docker Port Breaks Web UI

### ISSUE THREAD

**Issue by jmcree** [pirate/ArchiveBox#527]
I'm on unraid and using the repository from nikisweeting/archivebox:latest
 
By default the docker uses port 8000. This is already taken on my system and when I try to change it to say port 5000, the webUI says it cannot reach this page. I have changed the port in the basic docker setting, specified the webUI url in the advanced docker settings to use port 5000 and told the server to run on 0.0.0.0:5000 in the console. What am I missing to get it to run on a different port?

**Comment by pirate** [comment]
What are the exact commands you're running to start it? Can you post your config file and some log output as well.

**Comment by jmcree** [comment]
Hey. You can close this.. I was just going though and getting all of the screenshots and logs for you and had an idea.. instead of putting "server 0.0.0.0:8000" in the docker settings I manually start the server from the console "archivebox server 0.0.0.0:8000". well, in my attempts to move it to port 5000, i was putting 5000 here too. I just started it from using the 8000 (what i now realize the internal port, not my bridge port) and it pulls right up.

Now if I can only figure out how to use tags or categorize the different sites.

**Comment by cdvv7788** [comment]
Tags can be added from the admin in the latest version. You can build the image yourself with the contents of `master`
 while we release a new image.
