### ISSUE TITLE
New index single-source-of-truth instead of JSON: SQL Database w/ migrations

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#57]
If I end up writing a backend, Django is not a bad choice because the migrations system would allow us to keep an up-to-date queryable SQLite database with all the links.

Running the archive.py script at any point would update the schema to the latest version, because it has the entire migration history from the time the index was last exported till now.

On every run, the json can be re-exported and the files updated if necessary.  The SQLite database would also allow for fast searching and indexing of the links.

Files can be foreign-keyed on both uuid and their sha-512 hash to globally deduplicate and enable sharding later.

**Comment by pirate** [comment]
Upcoming design: https://docs.google.com/presentation/d/17gPkY6chAzDDXCce1QkTdRwl2nChESdjfibal-n8TgM/edit?usp=sharing

**Comment by FiloSottile** [comment]
SQLite also come with nice full-text search (FTE5) which works even if you don't store the actual content in it, so you can have all the outputs in files, and use SQLite as the index and search solution. (Would go well with #69.)

**Comment by pirate** [comment]
I experimented with ElasticLunr earlier but SQLite's FTE5 looks like a great alternative.  If we use Django it'll be db-agnostic and we can do full-text search on both SQLite and Postgres.

**Comment by cdvv7788** [comment]
`django` branch has progress in this regard. sqlite database is already working along the legacy indexes.

**Comment by pirate** [comment]
Closing this because as @cdvv7788 said, the `django` with the next release has a full sqlite3 db with migrations. We can work on making it the single-source-of-truth gradually over several subsequent versions. Until then it will use all three indexes together.
