### ISSUE TITLE
Simple docker container for bookmark-archiver

### ISSUE THREAD

**Issue by pirate** [pirate/ArchiveBox#62]
Once the backend/proxy portion is done, many people have asked for a docker container to run it.

**Comment by aurelg** [comment]
Here's a quick & dirty attempt from a Docker newbie:

```
# Build with
#
#     docker build -t bookmark-archiver .
#
# Run with
#
#     docker run -v $(pwd):/data bookmark-archiver <bookmark_file>
#

FROM python:3.6-alpine

RUN \
  apk --no-cache update \
  && apk --no-cache upgrade \
  && apk add chromium wget git \
  && rm -rf /var/cache/apk/* /tmp/*

ENV CHROME_BINARY chromium-browser

RUN \
  pip install requests

ENV BOOKMARKARCHIVERDIR /bookmark-archiver
ADD . $BOOKMARKARCHIVERDIR

ENV DATADIR /data
WORKDIR $DATADIR

ENTRYPOINT ["/bookmark-archiver/archive"]
```

For some reason, `chromium-browser` segfaults, though. Any idea?

**Comment by pirate** [comment]
Always creating `./output` inside `bookmark-archiver/` is the expected behavior right now, but I could change it to output to current dir, I didn't do that initially because the main use case for having multiple output folders is if they were hosting this as a service, and I want to eventually do that myself and charge for it so I can fund development of this project 😁

**Comment by aurelg** [comment]
I haven't fixed the bug yet, but hacked my own version: [linkbak](https://github.com/aurelg/linkbak).

**Comment by aurelg** [comment]
Bug fixed on [linkbak](https://github.com/aurelg/linkbak/blob/master/Dockerfile), here's [the relevant Dockerfile](https://github.com/aurelg/linkbak/blob/master/Dockerfile). I ended up using another base image (`stretch-slim` instead of `alpine`), but I think it's not related. I had to tweak around sandboxing (`--no-sandbox`) and users/permissions to make it work.

**Comment by pirate** [comment]
I've now added a Dockerfile on master that works.  A docker-compose.yml example with nginx to server the archive will come next.

**Comment by pirate** [comment]
CC: @hannah98 @ivar @ilvar @Strubbl @aurelg 

You can use the new official image like so:

```bash
docker build github.com/pirate/bookmark-archiver -t bookmark-archiver
docker volume create archiver-output
docker run -v archiver-output:/home/chromeuser/app/archiver/output bookmark-archiver 'https://getpocket.com/users/nikisweeting/feed/all'
```

It's not perfect yet, I still have to make the ergonomics better for passing in link files to parse, right now you have to put them in the output volume and then reference them by their path inside the container to get BA to find them:
`docker run -v archiver-output:/home/chromeuser/app/archiver/output bookmark-archiver /home/chromeuser/app/archiver/output/downloads/path-to-links.json`

You're welcome to submit PRs if you find things that can be fixed/improved!

**Comment by pirate** [comment]
Closing this because it's been released and working fairly well for a while now: https://github.com/pirate/ArchiveBox/wiki/Docker
