### ISSUE TITLE
Archive Method: Full page height screenshots

### ISSUE THREAD

**Issue by swhib** [pirate/ArchiveBox#70]
to achieve this I set the RESOLUTION to '1440,10000' which usually seems to work. But this there a more elegant, proper way to do this?

btw: your donation page sounds like you look mainly for big and recurring contributions. Are you also interested in small one-time donations ($10/20)?

**Comment by pirate** [comment]
I am interested in small recurring donations, thanks! Although I am more interested in long-term grants, any little bit helps!

Firefox has a way of doing full-page screenshots but Chrome does not iirc.  We can leave this ticket open to track progress until Chrome has it available.

**Comment by pirate** [comment]
Reopening this to track using puppeteer to do real dynamic full page height screenshots.
