### ISSUE TITLE
archive from a session buddy export fails

### ISSUE THREAD

**Issue by thewriteway** [pirate/ArchiveBox#84]
It doesn't seem to support session buddy JSON or html output.

This is chrome tool session buddy - https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko

When running the archive tool it produces an error message says no link could be found.

please see extract output sample of a session buddy html file:

[session_buddy_export_2018_07_29_08_12_20.txt](https://github.com/pirate/bookmark-archiver/files/2238616/session_buddy_export_2018_07_29_08_12_20.txt)

**Comment by pirate** [comment]
Run it through this bash one-liner and then try importing it:

```bash
perl -pe 's/(.+?)(<a href=")?(http.+?)?(" target="_blank">.+<\/a><\/li>)?$/<li><a href="$3" time_added="1400000000" tags="">$3<\/a><\/li>/gm' < session_budy_export.html > fixed_export.html
./archive fixed_export.html
```

**Comment by thewriteway** [comment]
Sure, will try this out as well. Thanks

**Comment by pirate** [comment]
Try it now, it should be working on the latest master.  Comment back if you're still having issues and I'll reopen the ticket.
