### ISSUE TITLE
Apple News articles = 404

### ISSUE THREAD

**Issue by benfishbus** [pirate/ArchiveBox#90]
Example:
https://apple.news/AvnQPql9kSqG1GOqYdCQTiA

Resolves in browser, but bookmark-archiver reports:
Failed: Exception 404 Not Found

Known issue?

**Comment by pirate** [comment]
It will report a 404 if any of the assets on the page 404'ed (e.g. images/css/etC), not just the main html page.  Can you check the archive and see if the local archive of the apple news article is present and working?

**Comment by pirate** [comment]
I'm closing this since it can probably be fixed by changing [`USER_AGENT`](https://github.com/pirate/ArchiveBox/wiki/Configuration#WGET_USER_AGENT).
