### ISSUE TITLE
chromium-browser is available as chromium

### ISSUE THREAD

**Issue by Strubbl** [pirate/ArchiveBox#99]
In some Linux distros, e.g. Archlinux, the executable for the Chromium browser is available as `chromium` and not as `chromium-browser`.
It would be nice, if bookmark-archiver can support this.

**Comment by pirate** [comment]
Sure, this is easy to fix.  Thanks for reporting!

**Comment by pirate** [comment]
This is working in 5b6c768, sorry for the delay.  I've also made it automatically check for a bunch of other chrome binary locations too.
